### ISSUE TITLE
Support for "WITH" clause

### ISSUE THREAD

**Issue by svitthaldas** [go-spatial/tegola#1006]
Hello, 
The query i am using goes something like:
`WITH z AS (
	SELECT zoom_from_denominator(!scale_denominator!) AS zoom
)
SELECT 
	ST_AsMVTGeom(ST_Transform(geometrie, 4326), !BBOX!) AS geometrie 
FROM 
	${DB_SCHEMA}.bathymetry_layers
WHERE 
	(
		(z.zoom = 1 AND layer = 1 AND select_class = 1) OR 
		(z.zoom BETWEEN 2 AND 3 AND layer = 4 AND select_class = 2) OR 
		(z.zoom = 6 AND layer = 7 AND select_class = 3) OR 
		(z.zoom BETWEEN 7 AND 9 AND layer = 9 AND select_class = 3)
	)
	AND geometrie && !BBOX!`

But i am getting the follwing error: 
**_Error: could not register providers: could not generate sql, for layer(bathymetry_01): ERROR: syntax error at or near "WITH" (SQLSTATE 42601)_**

Is there any workaround for this, other than using the "zoom_from_denominator" function repetatively?

**Comment by iwpnd** [comment]
you can try wrapping all of it in:

```
SELECT * FROM (your_query)
```

**Comment by svitthaldas** [comment]
Hello @iwpnd , 
Your suggestion worked. Thank you.
