### ISSUE TITLE
add support for username for redis as cache in tegola config

### ISSUE THREAD

**Issue by ibrahimjel** [go-spatial/tegola#1010]
Hi,
I am using tegola with redis as cache type. my redis DB has username and password to authenticate with. when put in address like this URL `redis://<username>:<password>@redis:6379`, tegola throw exception 

> could not register cache: address  `redis://<user>:<password>@redis:6379`: too many colons in address

would be great to introduce new field `username` in [redis.go](https://github.com/go-spatial/tegola/blob/master/cache/redis/redis.go#L63).

**Comment by iwpnd** [comment]
I can take a look tomorrow. I’m however surprised to read this. Pretty sure we use it with credentials too.

**Comment by iwpnd** [comment]
You can use the uri like you did. Make sure your password does not contain a colon though. If this does not work correctly I can take a look.

**Comment by ARolek** [comment]
@ibrahimjel here's what seems like a related issue in the driver: https://github.com/redis/go-redis/issues/2870

Try removing `redis://` from the connection string.

**Comment by iwpnd** [comment]
As far as I can see we do not support the uri after all. Probably something we should do similar to the change we did to Postgres a while back? @ARolek 
I mean deprecating the host name in v0.21.0 and removing it in favor of the uri in v0.22.0?

**Comment by ARolek** [comment]
@ibrahimjel the one and only @iwpnd implemented connection string handling for redis! You can grab a binary to test it out via the GH Action: https://github.com/go-spatial/tegola/actions/runs/11917492487. Config documentation has also been updated: https://github.com/go-spatial/tegola/tree/master/cache/redis

Please report back how this works for you.

**Comment by iwpnd** [comment]
`Username` is the same as `REDIS_USER_TEGOLA`. Make sure your environment is properly populated and [your redis instance actually requires a password](https://github.com/redis/redis/issues/13437).
