### ISSUE TITLE
v0.21.0 broke web interface rendering

### ISSUE THREAD

**Issue by four43** [go-spatial/tegola#1022]
I use the docker image `gospatial/tegola:v0.21.0` and the upgrade from 0.20.0 to 0.21.0 broke the web interface for me. 

It's making a request to `http://capabilities/mvt_world.json` (missing the localhost:9090 I have as my basepath). This results in a totally broken map. My layers still show correctly but the rest of the interactive maps is broken.

**Comment by ARolek** [comment]
@four43 I hit this same issues yesterday and I'm working on a fix. Thanks for the report. I should have a fix in soon.

**Comment by ARolek** [comment]
@four43 I just sent in a PR to address this issue along with the outstanding ui vulns. Give it a test if you have a chance: https://github.com/go-spatial/tegola/pull/1023

**Comment by four43** [comment]
This was super easy since you provide a Dockerfile :heart: 

When querying the index (or really, nothing, the just http://localhost:9090) all I get back is:

```
<!doctype html>
<meta name="viewport" content="width=device-width">
<pre>
<a href=".keep">.keep</a>
</pre>
```

.... odd. Looking into your PR to see why...

**Comment by ARolek** [comment]
@four43 I haven't merged the PR into `master` yet. I will do that today, but you would need to pull down the branch and build the container yourself to test the PR. I will circle back once I merge into `master`. Btw, are you using a `uri_prefix` in the `webserver` config at all?

**Comment by four43** [comment]
No, pretty basic config. Just using the Docker image. 

I was just struggling to build the image and to find it in your GitHub actions. I'm not terribly familiar with golang which is my main problem :)

**Comment by ARolek** [comment]
@four43 You can test the unreleased docker container (but with what's in `master`) by pulling the `edge` tag: https://hub.docker.com/r/gospatial/tegola/tags

**Comment by four43** [comment]
How is that built? Is that in Github actions?

**Comment by ARolek** [comment]
> How is that built? Is that in Github actions?

Yes. Here's the action: https://github.com/go-spatial/tegola/actions/runs/12472282702/job/34810822636 The step is called "Publish docker edge container"

**Comment by four43** [comment]
Ah that's what I was missing. All those build args defaulted to not working for what I was trying to test. 

ANYWAY

The important part was you got the fix! Thank you so much!

**Comment by ARolek** [comment]
@four43 glad it's working for you! We have one more bug fix then I will cut a patch release.
