### ISSUE TITLE
Allow path prefix to be configured

### ISSUE THREAD

**Issue by mojodna** [go-spatial/tegola#136]
When running behind a reverse proxy, endpoints may be prefixed (e.g. `/tiles/`). Tegola should have the ability to provide an alternate path prefix to match the proxied prefix when it doesn't match Tegola's default (`/`).

(As both an option in the config TOML and as a command line arg.)

**Comment by ARolek** [comment]
how is this usually handled? It seems to me the proxy should drop the prefix rather than push the responsibility to tegola.

**Comment by mojodna** [comment]
The proxy does drop the prefix, so the app is fully unaware of it (it sees `/` where the client requested `/`). I know Apache can be configured to rewrite URLs on the way out, but rewriting responses is something I'd rather stay away from.

The need is for URL generation, not handling.

**Comment by ARolek** [comment]
You're talking about the URLs returned by the capabilities endpoint?

**Comment by mojodna** [comment]
Yes.

**Comment by ARolek** [comment]
tegola supports a config var of `hostname` which could be used for this requirement, though that's not the most elegant solution it would work near term.

**Comment by ARolek** [comment]
After discussing this with @mojodna we can accomplish this by supporting the query string `uriprefix` on the `/capabilites/` endpoints.
