### ISSUE TITLE
HTML code example for mapbox-gl

### ISSUE THREAD

**Issue by emakarov** [go-spatial/tegola#141]
Hello,
could you kindly write a HTML example same as you did for bonn data for mapbox-gl?

**Comment by ARolek** [comment]
@emakarov absolutely! In the mean time, you can see the mapbox-gl code we use for demo.tegola.io [here](https://github.com/terranodo/tegola-osm/tree/master/docs/mapbox)

**Comment by emakarov** [comment]
@ARolek thanks. looking forward to have a look at example

**Comment by ojlamb** [comment]
@emakarov Not sure if you're still looking for an example, but here you go.

`<!DOCTYPE html>
<html>

<head>
	<meta charset='utf-8' />
	<title></title>
	<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
	<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.js'></script>
	<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
	<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.css' rel='stylesheet' />
	<style>
		body {
			margin: 0;
			padding: 0;
		}

		#map {
			position: absolute;
			top: 0;
			bottom: 0;
			width: 100%;
		}
	</style>
</head>

<body>

	<div id='map'></div>
	<script>
		mapboxgl.accessToken = 'pk.eyJ1IjoicmVkem9uZXNvZnR3YXJlIiwiYSI6IkNKNXhPNkUifQ.yPI1bZL3nEvDFbdQjeTB-A';
		var map = new mapboxgl.Map({
			container: 'map',
			style: 'mapbox://styles/redzonesoftware/cj7hzazjl54aw2rnirxbcz44x',
			center: [7.0982, 50.7374],
			zoom: 11
		});

		var nav = new mapboxgl.NavigationControl();
		map.addControl(nav, 'top-right');

		map.on('load', function() {
				map.addSource('zones', {
					'type': 'vector',
					"tiles": ["http://localhost:8080/maps/zoning/{z}/{x}/{y}.vector.pbf?"],
					"tolerance": 0
				});

				map.addLayer({
					"id": "road",
					"source": "zones",
					"source-layer": "road",
					"type": "line",
					"paint": {
			             "line-color": "#000000",
			             "line-width": 1
			         }
				});

				map.addLayer({
					"id": "main_road",
					"source": "zones",
					"source-layer": "main_roads",
					"type": "line",
					"paint": {
						 "line-color": "#FFA362",
						 "line-width": 2
					 }
				});

				map.addLayer({
					"id": "lake",
					"source": "zones",
					"source-layer": "lakes",
					"type": "fill",
					"paint": {
						"fill-color": "#71CFEE",
					 }
				});


		});
	</script>

</body>`

**Comment by emakarov** [comment]
@ojlamb thanks!
will definitely give it a try

**Comment by zhl11b** [comment]
@ojlamb I think it's not right,even add source "zones",it use mapbox official tile

**Comment by brianbancroft** [comment]
@zhl11b I was able to get it to load as per the example once I added my Mapbox token, no problem here.
