### ISSUE TITLE
Viewer: Support switching between multiple maps

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#159]
Tegola can be configured to server multiple maps. The viewer does not currently have full support for a config with multiple maps.

**Comment by ezk84** [comment]
In the current version, I can see the multiple maps on the viewer but cannot select them to be shown.

**Comment by ARolek** [comment]
@ezk84 correct. It's yet to be implemented in the client side app. Want to take a stab at it? It's all built using vue.js and can be found [here](https://github.com/go-spatial/tegola/tree/master/server/static)
