### ISSUE TITLE
Rendering artifact

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola#179]
There are a couple of extra lines showing up in this natural earth country polygon dataset. They disappear once you zoom in.
![tiledebug](https://user-images.githubusercontent.com/5266205/32741352-317cd918-c863-11e7-80a3-35263711b0bf.png)

**Comment by gdey** [comment]
@PetersonGIS Thanks for reporting this. Will look into it. I believe it's the makevalid, for some reason on some geometries does not generate the last triangle. I'm working on trying to figure out why this is, as well as why it sometimes does not eliminate an unneeded cutout ring.

**Comment by gdey** [comment]
I believe this should be resolved in #268
