### ISSUE TITLE
Make tegola.Tile bounding box consistent.

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/tegola#189]
The bounding box in a Tile claims to be in WebMercator coordinates, but the bounding box presents its data as though the origin is the top left.

Write tests for FromWebMercator(), ApplyToPoints(), webmercator.PToLonLat(), to verify that these functions are converting from a WebMercator axis (origin off African coast) rather than a Tile axis (origin at top-left of world map)

After verifying, update coordinate order of BoundingBox & update corresponding tests.

This may break other code which uses tegola.Tile().

**Comment by JivanAmara** [comment]
Tests for:
[ ] FromWebMercator()
[ ] ApplyToPoints()
[ ] PToLonLat()

**Comment by gdey** [comment]
#357 redoes bounding box. It is no longer claiming to be the top left, rather a bounding box is now just the minx, miny, maxx, and maxy values. To get the top-left point of the tile use the Bounds methods, which will return (west, north, east, south) coordinates.
