### ISSUE TITLE
Tegola (version not set) with 0.5.0

### ISSUE THREAD

**Issue by erictheise** [go-spatial/tegola#233]
I just fired up the latest release and in `/capabilities` and the built in map browser I'm seeing _(version not set)_ instead of _0.5.0_.

`tegola_darwin_amd64`.

**Comment by ARolek** [comment]
@erictheise thanks for the report. I will check the CI scripts to see what's going on.

**Comment by ARolek** [comment]
@erictheise I re-released v0.5.0 since this was not really a functional bug fix. You can download the updated bins on the release page. Thanks for the report.

**Comment by ARolek** [comment]
Appears this is happening again.

**Comment by ARolek** [comment]
This is fixed in v0.9.0. Hopefully forever.
