### ISSUE TITLE
Clean up boundbox

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola#270]
There are several implementations of bounding box/ or extents. consolidate and clean these various implementations and the code the depends on them. Renaming it to Extents by the end.

Part of #269

**Comment by gdey** [comment]
Going through the various bounding box (and extent) implementations I come to the conclusion that the way the clipping algorithms is using bounding box is wrong. They are assuming that a bounding box is made up of two points the (upper left) and (lower right) which in mvt happen to be the minx, miny and maxx, maxy points. I thinking it makes more sense to have bbox be [4]float64 as it's not really two points as I was previously thinking.

**Comment by ARolek** [comment]
@gdey I'm not quite sure I follow. What's the difference between `[2][2]float64` and `[4]float64`? Seem like you need to know what is the min / max is if you're going to access the values directly or you will need to leverage MinX/Y() MaxX/Y() methods. If we stick with `[2][2]float64` we can leverage the `geom` package. Maybe a `New([2]float64, [2]float64)` would be helpful and it could figure out what the min / max points should be?
