### ISSUE TITLE
Server doesn't start when layer sql contains this query

### ISSUE THREAD

**Issue by sanfilippopablo** [go-spatial/tegola#296]
I'm trying to make coverage overviews for a layer when zoom < 13. I tried this:
````sql
SELECT ST_AsBinary(ST_Union(ST_Buffer(polygon::geography, 15)::geometry)) AS polygon, MAX(id) as gid FROM vectors WHERE polygon && !BBOX!
````
but the server logs `config.go:161: Loading local config (config.toml)` and it just hangs there, never starting to listen for connections.

With this query, it works fine:
````sql
SELECT ST_AsBinary(ST_Buffer(polygon::geography, 80)::geometry) AS polygon, MAX(id) as gid FROM vectors WHERE polygon && !BBOX!
````
That makes me thing that ST_Union is the problem.

Also, is it a bad practice to do aggregation here?

**Comment by sanfilippopablo** [comment]
Correction: it starts, after 10 minutes. I checked DB activity and the DB instance was at CPU 100%, for the whole tegola starting time. That means tegola is doing some expensive query at startup?

**Comment by ARolek** [comment]
@sanfilippopablo when tegola starts up it tries to run all the queries to make sure they're successful before it starts serving. This is to avoid issues during tile request time. Have you tried running these queries in PostGIS to check their performance? Also do you have indexes on your geometries? 

I suspect the ST_Union query is the culprit and causing PostGIS to work really hard. This operation is going to happen for all the tiles so it's better to get it optimized now or your tile requests will be slow.

**Comment by sanfilippopablo** [comment]
I tried it for tiles and it was really fast, but if it's doing it for the whole world, I can imagine it taking too long. Yes, I have an index on the geometry. I think I will do `ST_Buffer(polygon::geography, 80)::geometry)` previously into a new `overviews` table.

**Comment by ARolek** [comment]
It does do it on a 0/0/0 tile but also includes a LIMIT 1 so usually it’s super fast. If you turn on the execute sql debug you should be able to see the query and test it in postgis. Check out http://tegola.io/debugging/#environment-variables

**Comment by sanfilippopablo** [comment]
Closing as this is not an issue with tegola.
