### ISSUE TITLE
Add support for a redis caché, to the caché system.

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola#300]
Moving over feature request from tegola-osm/#40 for @peldhose .

**Comment by peldhose** [comment]
ok thanks ... 👍
how much time it may take to implement feature ?? any roadmap or timeline??

**Comment by ARolek** [comment]
@peldhose we have a few other priorities so it's not on the immediate roadmap. Would you be interested in trying to build the implementation? I can point you to where in the code you would do the work.

**Comment by peldhose** [comment]
mmm ok , actually i coded years before in java n php.anyway give me some guidelines i will try myself to implement (u guys should help me ).
also we would like to use tegola for production purpose, any suggestions ??

**Comment by gdey** [comment]
@peldhose If you have any questions ask, and I'll do my best to help you out. To learn Go you can start with: 
https://tour.golang.org/welcome/1

As far as implementing the caché:
Here is are a couple popular redis libs: 
https://godoc.org/github.com/garyburd/redigo/redis
https://godoc.org/github.com/go-redis/redis

I'm not sure which is better. 

To add a new caché, it will need to register with the caché system located here:
https://github.com/terranodo/tegola/tree/master/cache

Looking at the file caché you can see it doing the registration with the caché system here:
https://github.com/terranodo/tegola/blob/master/cache/filecache/filecache.go#L24,26

Each caché must the caché interface:
https://github.com/terranodo/tegola/blob/master/cache/cache.go#L12-16

So, all you have to do it implement the caché interface for the storing, retrieving, and purging. Register with the registration function, which you provide a name and an InitFunc (https://github.com/terranodo/tegola/blob/master/cache/cache.go#L112) that will take a configuration `map[string]interface{}` and return the caché object.  The name is what user use in the configuration file, so it is good to turn that into a constant (https://github.com/terranodo/tegola/blob/master/cache/filecache/filecache.go#L17).  

You can use the filecache ( https://github.com/terranodo/tegola/tree/master/cache/filecache ) as a guide. 

Also, base your work on the (v0.6.0 branch). The code is better commented as well, and it will soon be master.

If you have any further questions don't hesitate to ask.

**Comment by peldhose** [comment]
ok, let me go through n need some time to understand GO way ... anyway, i will try my best.

 we would like to use tegola for production purpose, any suggestions or concerns i should consider  ??

**Comment by ear7h** [comment]
@peldhose if you haven't gone through too much trouble already I could implement this

**Comment by peldhose** [comment]
no probs @ear7h pls proceed.
I just started, need more time than I expecting.

**Comment by ARolek** [comment]
@peldhose looks like you're in luck! @ear7h implemented the redis cache and it will be released with v0.6.0 due to be cut this week. If you want to try it out beforehand you can build from the v0.6.0 branch.

**Comment by epl-admin** [comment]
WOW... thank you @ear7h ... Awesome..... i will try out for sure ...

**Comment by peldhose** [comment]
hey ,i was testing redis.
1.Redis documentation is very less (how to implement )
2.then here i found how to (https://github.com/go-spatial/tegola/tree/master/cache/redis) 

> tegola.toml file,
> [webserver]
> port = ":8080"
> [cache]
> type="redis"
> network="tcp"
> address="localhost:6379"
> 
but i got error saying : " 2018/02/28 09:31:07 root.go:89: No cache backends registered by the cache type: (redis) "

tegola Version is 6.0

**Comment by gdey** [comment]
lol, we build it but forgot to import the cache package into the system. I'll get a v0.6.1 out with this. Sorry.

**Comment by gdey** [comment]
@peldhose Okay, v0.6.1 should now work as expected.

**Comment by peldhose** [comment]
hey guys... I have tested out .. it works flawlessly ... awesome work bro @gdey @ARolek  ... now tegola flies like flight .... super excited ...

**Comment by peldhose** [comment]
hey guys,, 
i have implemented redis with tegola , and its running super fast .. but after 2 days of running, now i feel its got too slow ... tegola takes too much time to retrive tiles .. can somebody check on this?

**Comment by ARolek** [comment]
@peldhose can you give us any more details? How many tiles are in your cache? Can you provide some insight on the machine specs and resource usage. I'm looking to figure out how we can recreate the problem.

**Comment by peldhose** [comment]
hey sorry .. its solved . it was because of redis,when i checked tegola logs,it was telling me to chk redis logs for some issues.So redis gave me this error " redis Failed opening the RDB file root (in server root dir /var/spool/cron) for saving: Read-only file system ".
so i solved it, now running fast . thanks for quick reply ..
