### ISSUE TITLE
Figure out why QGIS Vector Tiles Reader compatibility plugin is not able to read our tilejson url.

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola#304]
Add the following end point:
`/capabilities/$map/metadata.json`

Where the json returned follows the follow spec:
https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/Help#metadatajson

This will allow QGIS to access tiles from Tegola directly.

**Comment by gdey** [comment]
Would this be in the cache directory? Or at a particular URL? I guess how do you envision this being used?

**Comment by PetersonGIS** [comment]
This might not be an answer, but here's what I was trying to do:
![pluginscreenshot](https://user-images.githubusercontent.com/5266205/36270265-7a5f3b3e-1238-11e8-90fb-b507f49a8bff.JPG)
After clicking save, then connect, it shows this:
![connect](https://user-images.githubusercontent.com/5266205/36270280-86888bb8-1238-11e8-802a-14149f977145.JPG)
I have also tried with this url: https://osm.tegola.io/maps/osm/{z}/{x}/{y}.pbf.
Eventually, if we could get the plugin to work with our tiles and styles then it will help us transform our styles for qgis much more quickly. I imagine there will be some things that will still need to be hand-styled in qgis but not as many as if we started from scratch.

**Comment by ear7h** [comment]
From the spec, it's my understanding that the endpoint should be `/maps/:map/metadata.json` for the metadata since the tiles are being served from `/maps/:map/:z/:x/:y.pbf` and the plugin assumes a specific file structure.

**Comment by ear7h** [comment]
@PetersonGIS After looking into this, I believe the endpoint you should use is `/capabilities/:map` without the trailing `metadata.json`. Let me know if this still doesn't work.

**Comment by ear7h** [comment]
I just checked this against `https://osm.tegola.io/capabilities/osm` and it gave a `Loading error: SSL handshake failed`. So that is something new to look into...

**Comment by PetersonGIS** [comment]
Thanks for the tips @ear7h . I finally got the QGIS Vector Tile Plugin to load up some of our vector tiles with the following URL: https://osm.tegola.io/capabilities/osm. I wonder if the server was down when you tried it before. Can you double-check that it is working for you at this time?

**Comment by ARolek** [comment]
@PetersonGIS can you send over a screen shot of your settings? I still get an error message "None" when trying to connect.

**Comment by PetersonGIS** [comment]
![qgis_vector_tile_plugin](https://user-images.githubusercontent.com/5266205/37996704-cd5600c2-31d5-11e8-9b43-731a7247d116.JPG)

**Comment by PetersonGIS** [comment]
This one is a better screenshot. It is connecting to the TileJSON URL here and providing all the layers. (Note that with this plugin it is best to load a layer such as ne_10m_admin_0 first so you can zoom way in first.)

Interestingly it is not loading up the style.json at all, except for the background color. I still haven't figured out that piece of the puzzle. So the colors shown here are definitely not the camo style.

![qgis_vector_tile_plugin2](https://user-images.githubusercontent.com/5266205/37996884-7b99a33c-31d6-11e8-915f-0eb2ebaf50b3.JPG)

**Comment by ARolek** [comment]
strange. I still can't get it to load on macOS. You're using windows, right?

**Comment by PetersonGIS** [comment]
Yes

**Comment by PetersonGIS** [comment]
Try removing the tile layers and reloading after using Vector > Vector Tiles Reader > Clear Cache. Or create a new connection and see if that works.

**Comment by erictheise** [comment]
@PetersonGIS, I've (re)installed QGIS 2.18.15 along with the Vector Tiles Reader QGIS Plugin on OS X. I'm using `http://localhost:7070/capabilities/osm.json` as the TileJSON URL and `http://localhost:8080/nautical_active.json` as the GL Style JSON URL and the combo looks promising.

What kills the load is

```
2018-04-01T13:53:18	0	Creating styles from: http://localhost:8080/nautical_active.json
2018-04-01T13:53:18	0	Styles will be written to: /var/folders/q2/3wp7snyh8xn46j008k8wdqr80000gn/T/vector_tiles_reader/styles/tegola-openseamap local
2018-04-01T13:53:18	2	Style generation failed: (<type 'exceptions.ValueError'>, ValueError("invalid literal for int() with base 10: 'wetland'",), <traceback object at 0x129830cb0>), Traceback (most recent call last):
			  File "/Users/erictheise/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 409, in _create_styles
			    core.generate_styles(data, output_directory, web_request_executor=self._load_style_data)
			  File "/Users/erictheise/.qgis2/python/plugins/vector_tiles_reader/ext-libs/mapboxstyle2qgis/core/__init__.py", line 53, in generate_styles
			    styles = process(style_json)
			  File "/Users/erictheise/.qgis2/python/plugins/vector_tiles_reader/ext-libs/mapboxstyle2qgis/core/__init__.py", line 89, in process
			    qgis_styles = get_styles(l)
			  File "/Users/erictheise/.qgis2/python/plugins/vector_tiles_reader/ext-libs/mapboxstyle2qgis/core/__init__.py", line 277, in get_styles
			    all_values.extend(get_properties_by_zoom(layer, "paint/fill-color", is_color=True, default="rgba(0,0,0,0)"))
			  File "/Users/erictheise/.qgis2/python/plugins/vector_tiles_reader/ext-libs/mapboxstyle2qgis/core/__init__.py", line 498, in get_properties_by_zoom
			    "zoom_level": int(lower_zoom),
			ValueError: invalid literal for int() with base 10: 'wetland'
```

and indeed the hunk of JSON style for 'wetland' looks suspicious.

```
    {
      "id": "landuse_areas_z13",
      "type": "fill",
      "source": "osm",
      "source-layer": "landuse_areas",
      "minzoom": 13,
      "maxzoom": 24,
      "layout": {
        "visibility": "visible"
      },
      "paint": {
        "fill-color": {
          "property": "type",
          "type": "categorical",
          "default": "transparent",
          "stops": [
            [
              "wetland",
              "rgba(227, 233, 226, 1)"
            ],
```

Is this right? Every occurrence of `stops` I've come across has a numerical first value corresponding to a zoom level and the QGIS/Python error suggests it's expecting an integer.

**Comment by erictheise** [comment]
After more digging, our use of `"type": "categorical"`should allow for strings as stops. I [opened an issue](https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/194) at the plugin repo.

**Comment by erictheise** [comment]
I am concerned about the comment that this plugin ["was a semester student project which actually came to an end"](https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/78#issuecomment-329004390).

**Comment by PetersonGIS** [comment]
Yes, was just coming around to this idea of the plugin not being very stable right now and perhaps not being as useful as I originally thought. For example, I got one stylesheet to work with the plugin and then it promptly minidumped and shutdown when zoomed out. Thinking we may want to stop working on this for now. Thoughts?

**Comment by erictheise** [comment]
Well, _something's_ going to evolve to fill this niche and I could submit a pull request to cover this case. Can't tell if that's the only thing blocking us or just the tip of the iceberg.

**Comment by ARolek** [comment]
I agree with @erictheise, something is going to need to fill this niche. I also foresee an issue with parsing the new [Mapbox GL expressions](https://www.mapbox.com/help/mapbox-gl-js-expressions/). The `stops` syntax is being deprecated.

**Comment by roblabs** [comment]
Just checking in, and hoping to help out.  I found about this QGIS plugin because of this open issue (so thanks for the discussion)

----

Is this issue still open because
1) Tegola's TileJSON?
  * *e.g.,* http://localhost:8080/capabilities/cities.json
  * which is seems compliant as `"tilejson":"2.1.0"`,  or,
2) Mapbox GL expressions?  #issuecomment-377996308
  * I assume the issue is open due to 2)  — the specific nautical Style with stops that @erictheise refers to.

**Comment by ARolek** [comment]
@roblabs to be honest, I'm not quite sure where the issue is. I would suspect on the style definition as tegola is returning back the correct tileJSON. I have not had much of a chance to dig into it though. Last I recall, the plugin was a student project and may have lost momentum. It would be an amazing addition to the QGIS ecosystem though.

**Comment by timlinux** [comment]
I'm getting similar issues. Thanks to @ear7h 's suggestion I used the following for my connection string:

```
http://localhost:9091/capabilities/swellendam
```
(I had initially tried an {x}/{y}/{z} style url which gave the  'none' error as shown above.)

And now I see my test layers:

<img width="918" alt="screen shot 2018-06-28 at 00 00 22" src="https://user-images.githubusercontent.com/178003/42002078-48978822-7a66-11e8-926b-99c1c7f33a3f.png">

However when I add these to my project, they show up as empty QGIS layer groups:

<img width="988" alt="screen shot 2018-06-27 at 23 54 43" src="https://user-images.githubusercontent.com/178003/42001958-e633e5cc-7a65-11e8-8049-db2ee345474d.png">

**Comment by timlinux** [comment]
Just an update that by tweaking my  id fieldname to use fid as below (I am serving the tiles from a geopackage):

```
id_fieldname = "fid"
```

my vector tiles served from tegola now work:

<img width="1259" alt="screen shot 2018-06-28 at 08 23 06" src="https://user-images.githubusercontent.com/178003/42017602-f547234a-7aaf-11e8-9453-4efca120fd86.png">

**Comment by ARolek** [comment]
@timlinux nice! is this with QGIS 3.0? It would be nice to have some of these screenshots in a guide under the tegola.io docs. Would you be able to help with that?

**Comment by stvno** [comment]
I just checked with 3.3-dev and it recognizes them just fine

**Comment by ARolek** [comment]
I just tried this on 3.2 and it's also working great! I'm going to call this issue closed!
