### ISSUE TITLE
un-inferable geometry types prevent layer list from loading on tegola index page.

### ISSUE THREAD

**Issue by erictheise** [go-spatial/tegola#322]
I haven't been paying much attention to the layer list for the `seamark` project. When I last looked, it didn't load anything. I did a fresh build today and a few renderings trickle through but `syslog` gets many errors:

```
Feb 23 02:00:23 ip-172-31-9-101 dhclient[892]: bound to 172.31.9.101 -- renewal in 1507 seconds.
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: causeway_areas. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: communication_area. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: gridiron_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: inshore_traffic_zone_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: military_area_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: protected_area_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: radar_line. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: radar_range. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: recommended_route_centreline. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: recommended_traffic_lane. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: retro_reflector. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: sand_waves_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: sand_waves_areas. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: seaplane_landing_area_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: spring. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: submarine_transit_lane. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: separation_crossing. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: turning_basin_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: vegetation_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: vegetation_lines. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: vegetation_areas. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: vehicle_transfer_points. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: vehicle_transfer_areas. style defintion not generated
Feb 23 02:10:34 ip-172-31-9-101 env[32683]: 2018/02/23 02:10:34 standard.go:28: #0152018-02-23 02:10:34 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: water_turbulence_areas. style defintion not generated
```

**Comment by erictheise** [comment]
Note also that _definition_ is misspelled.

**Comment by ARolek** [comment]
@erictheise that's to be expected. If tegola can't figure out the geometry type from your query then it can't generate a style and will log that warning. We're considering implementing a proper SQL parser so we can better handle this situation but that's going to take some time and is not a priority. 

I will get the misspelling fixed up. Thanks for reporting that.

**Comment by erictheise** [comment]
We have a schema defined by the `seamark` tagging hierarchy and our Imposm3 import works with that. When the import runs, `geometry` is set to Point, LineString, or Geometry depending on whether the `geometry` `type` is set to `point`, `line`, or `area`. So the database knows its geometry type.

The `[INFO]` message occurs when there is no data in the database for that `provider.layer`. It shouldn't really be true that it can't infer or determine the geometry type.

It is true that there may be no reason to define a style for that layer as there will be nothing to display at that instant. This truth may be unstable in the situation where an installation is processing OSM differences.

**Comment by ARolek** [comment]
If the query does not return any records tegola will not have a way to determine the geometry type. It would be nice if we could just read the geometry column for a table and use that but PostGIS allows the user to create geometries in SQL or the geometry types my be combined into things like GeometryCollections. Because of this we need to run the query and analyze the result set to determine the type. This process is not perfect as you have seen. 

There's a good thread going with @pnorman on #320 around this. We're open for ideas as the auto generated style is a great feature but modifying SQL without a proper parser is brittle.

**Comment by erictheise** [comment]
@ARolek, the real motivation for opening this issue is that it's occasionally the case that configured layers may not contain data. This can happen with standard OSM layers when using an extract and it is happening in the _seamark_ project where objects are defined in the schema but none are present even at the planet level.

This situation causes the info messages above to be logged but more importantly, it blocks loading the list of layers on the index page of the tegola instance. `vue.js` looks at `map.layers` from `/capabilities` but falls down because the `unable to infer geometry type for providerLayerName` layers haven't been added.

Simple fix would be to add them anyway and not `continue` from the `default` block in `handle_map_style.go`. A better fix would have some visual indicator that such layers contain no data so that a poor user won't search the globe looking for some. strikethrough on the layer name, perhaps, or making the link inactive...

There is a `metadata` attribute on `layer` that could flag this condition. Happy to work on this once I figure out how `go-bindata-assetfs` works.

**Comment by pnorman** [comment]
> If the query does not return any records tegola will not have a way to determine the geometry type.

But it shouldn't need it for anything, which is one of the points in #320. The only way to know the geometry type for an arbitrary layer is to ask the user.

**Comment by ARolek** [comment]
@pnorman I think that's the solution we're going to go with. I'm going to add support for defining the geometry type for a layer in the config which can be used instead of trying to infer the type. The autogenerated style is nice but does come with a lot of baggage.

**Comment by erictheise** [comment]
Someone can reopen this if it's pertinent but the front end code that went out with [v0.6.2](https://github.com/go-spatial/tegola/releases/tag/v0.6.2) addresses this issue as far as I'm concerned.
