### ISSUE TITLE
Enforce Right Hand Rule for linear rings in Polygons/MultiPolygons.

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/tegola#328]
Tegola's geometry spec follows the RHR for these geometries.  Incoming data doesn't always follow it.  Add a failure or rewrite the geometry on import to make sure the geom.Geometry types created do follow the rule.

@gdey @ARolek

**Comment by ARolek** [comment]
@JivanAmara forgot to bring this up but I believe the MakeValid processing ensures this. @gdey can you confirm? If so, then once that functionality has fully adopted the geom types this should be able to be called prior to calling json.Marshal()

**Comment by gdey** [comment]
Yes, the MakeValid ensures that things going through the make valid function will follow the right-hand rule.
