### ISSUE TITLE
For invalid x,y values we should return a non-200 response code. (400)

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola#334]
The X,Y values should be in the range of:
Each zoom is 2^z tiles wide, so 0 <= x < 2^z and 0 <= y < 2^z

If the x,y value is outside this range, return a 400 error code.

**Comment by pnorman** [comment]
z should also be constrained in a range - at the very least, positive.

**Comment by gdey** [comment]
We already have a check for -z values (https://github.com/terranodo/tegola/blob/v0.6.0/server/handle_map_zxy.go#L47 and https://github.com/terranodo/tegola/blob/v0.6.0/server/handle_map_layer_zxy.go#L49). This should enhance these checks.

**Comment by ear7h** [comment]
@gdey I can take this issue
