### ISSUE TITLE
Missing water polygon

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#348]
With TEGOLA_OPTIONS=DontSimplifyGeo and a self-built 08ddd8f (v0.6.0) I get

![image](https://user-images.githubusercontent.com/1190866/36930508-fe6ef598-1e56-11e8-95c5-f90688a70989.png)

In tile 6/10/22 some of the water is missing.

If I zoom in to z7 all the water loads in 7/20/44
![image](https://user-images.githubusercontent.com/1190866/36930615-8a80f0d4-1e59-11e8-99a0-43178753d5fb.png)

The 

I checked the DB and the polygons are present in the data, and they are, with fid=1701

![image](https://user-images.githubusercontent.com/1190866/36930575-9fbf09be-1e58-11e8-89fe-0b3f60d312b6.png)

Weirdly, it doesn't precisely correspond to what's missing

The layer that produces the problem is
```toml
  [[providers.layers]]
  name = "lz_water"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
      SELECT
          way
        FROM simplified_ocean_polygons
        WHERE way && !BBOX!
      UNION ALL
      SELECT
          way
        FROM planet_osm_polygon
        WHERE way && !BBOX!
          AND (waterway = 'riverbank'
            OR landuse = 'reservoir'
            OR "natural" = 'water')
          AND way_area > pixel_size(9)*4 -- working around tegola #343
    ) _
  """

...

[[maps.layers]]
name = "water"
provider_layer = "osm2pgsql.lz_water"
min_zoom = 6
max_zoom = 9
```
`row_number() OVER ()` guarantees that this isn't #337, but a different bug.

To isolate it I tried some SQL
```
create table ocean_test as select * from simplified_ocean_polygons where fid=1701;
```
And changed the layer SQL to
```sql
SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
      SELECT
          way
        FROM ocean_test
        -- WHERE way && !BBOX!-- tegola requires !BBOX! in the query, so give it one
    ) _
``` 
Hiding tile bounds to get a better view, I have

![image](https://user-images.githubusercontent.com/1190866/36930603-31812e2c-1e59-11e8-8013-b1a961c6f83c.png)

I highlighted some areas in the z6 tile
![image](https://user-images.githubusercontent.com/1190866/36930631-e34a7b36-1e59-11e8-8541-614a0d55e5bb.png)

These are either interior rings (i.e. islands) like the top one or bays, like the bottom one, reproduced below

![image](https://user-images.githubusercontent.com/1190866/36930635-1d6affa2-1e5a-11e8-8df9-3a12d2b049e5.png)

I checked and the geometry is both ST_IsValid and ST_IsSimple.

**Comment by gdey** [comment]
This looks like an issue with the MakeValid function. 
<img width="335" alt="screen shot 2018-03-05 at 11 56 59 am" src="https://user-images.githubusercontent.com/14805/36996916-d94d6c46-206c-11e8-9f15-1fccbffe6b9b.png">

I will look into this after I'm done with the current issue I'm working on.

**Comment by gdey** [comment]
@pnorman I would like to recreate this on my laptop so that I can figure out what is going wrong with the makevalid function. What data set are you using? 

Thank you,

Gautam.

**Comment by pnorman** [comment]
simplified_ocean_polygons which is http://data.openstreetmapdata.com/simplified-water-polygons-complete-3857.zip with a last modified of Mon, 26 Feb 2018 08:30:25 GMT

I've uploaded the result of `\copy ocean_test to ocean_test.csv` which you can load in

[ocean_test.txt](https://github.com/go-spatial/tegola/files/1798646/ocean_test.txt)

**Comment by gdey** [comment]
@pnorman just wanted to let you know I did start working on this, but I started having issues with my laptop, which Apple then took; so it will be around a week before I can get back to this.

**Comment by pnorman** [comment]
I've done a check of my tracked bugs, and this bug is no longer present in the 0.9.x branch.
