### ISSUE TITLE
config: environment variable sniffing matches strings with $ not at beginning

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#353]
A string like `foo = fdsjkl$Gfsdoi423kjfdfX$2Wdsa$dsfdsS$` with match `$G` with our current regex expression when it should be ignored.

**Comment by gdey** [comment]
I think we should get rid of the `$Foo` support and just do `${FOO}` that will make it easier to avoid these types of issues. Not perfect, but Will be better.

**Comment by ARolek** [comment]
This particular issue is because we're not sniffing for beginning of the string using the `${` would be an easier fix. Alternatively we can revisit looking into the `toml.Unmarshaller` interface. If we leverage the interface we will only need to sniff the value, not the key and the value. Downside is we need to wrap every type in our config to do this.

**Comment by gdey** [comment]
That is true, but in this case, where it was a password, it is possible that the password could have started with a `$` then it would not matter; it is less likely that a password starts with a `\${` and ends somewhere down the line with a `}\n`, still possible but less likely. 

Here is a play with my suggestion.

**Comment by sam-radiant** [comment]
Any update on this?

**Comment by ARolek** [comment]
@sam-radiant not quite yet. It's a priority to address though. We're likely going to drop env var support without braces. All env vars will need to look like `${MY_ENV_VAR}`.  I'm hoping we can make some progress on this starting next week.

**Comment by sam-radiant** [comment]
@ARolek Sounds good. I have a VERY temporary workaround. I'll make sure to only use ${} vars as well. Thank you!

**Comment by ARolek** [comment]
@sam-radiant just a heads up, we're almost done with this one. should hit the `v0.7.0` branch this week.

**Comment by ARolek** [comment]
@sam-radiant this has been merged into the v0.7.0 branch and will be part of the next release.
