### ISSUE TITLE
min_zoom and max_zoom are not optional

### ISSUE THREAD

**Issue by russss** [go-spatial/tegola#354]
If you omit them, they're both set to 0 in the tilejson. This seems to break the preview viewer and, at least with MapBox GL, results in only the 0 zoom level being rendered, which results in some interestingly abstract maps.

Either the docs/config parser need changing to make these required, or we need some sensible defaults...

**Comment by ARolek** [comment]
@russss interesting bug. Just so I understand your config, you want every layer to render at every zoom so therefore you did not set a min_zoom and max_zoom for the layers?

**Comment by russss** [comment]
Yeah, the docs say those config directives aren't required so I didn't include them!  In this case my data matches the OSM zoom ranges, and I was auto-generating the tegola configuration, so I didn't have any zoom range numbers to hand.

I think the simplest fix is just to make max_zoom default to something like 17 instead of 0.

**Comment by ARolek** [comment]
I could also potentially remove `max_zoom` if it's not set.

**Comment by gdey** [comment]
Well, we already have a hard-coded MaxZ of 22. So, if it's not there, I think it should default to this constant. With MinZ defaulting to 0.

**Comment by ARolek** [comment]
@gdey I like that idea. Let's go with it.
