### ISSUE TITLE
Use relative URLs in Tegola page

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#361]
The `/` page served by Tegola uses absolute URLs, e.g. `http://localhost:8080/capabilities/bolder.json`

This is a problem because in production it's very unlikely that it will match the URL. Instead, relative URLs should be used.

**Comment by ear7h** [comment]
The [webserver](http://tegola.io/documentation/configuration/#webserver) config section supports user defined host names.
cc @ARolek

**Comment by ARolek** [comment]
@pnorman we ran into an issue using relative URLs when the consumer of the TileJSON was not on the same domain as tegola. For example, using Maputnik to style tiles served by osm.tegola.io would not work without absolute URLs.

When going to production you can use the hostname config value that @ear7h referenced. This is also useful if tegola is behind a proxy that does not provide forwarding headers.

**Comment by pnorman** [comment]
> @pnorman we ran into an issue using relative URLs when the consumer of the TileJSON was not on the same domain as tegola

Is something interpreting the relative URLs as relative to the HTML page, rather than relative to the TileJSON? That sounds like a bug.
