### ISSUE TITLE
Chat room for discussion of Tegola

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#363]
Is there a good place for discussion of Tegola? Some projects use gitter.im (e.g. https://gitter.im/tangrams/tangram-chat)

Issue trackers are good for persistence and documenting stuff (as well as issues), but sometimes real-time chat feels more convenient.

**Comment by jj0hns0n** [comment]
We are all on the terranodo slack. Happy to invite you there. Having tried
all the alternatives to slack, we pretty much find them all inferior and
keep coming back to slack.

**Comment by pnorman** [comment]
I'm not enthusiastic with adding yet another chat platform, but I could get on slack. Can you send an invite link?

**Comment by gdey** [comment]
@pnorman did you get the invite form @jj0hns0n? Wondering if I can close this issue. Also, I hangout in the #tegola and #go-spatial channel on the gophers slack organization. I think we are trying to move everyone over to that as well.

**Comment by pnorman** [comment]
I haven't gotten an invite.

**Comment by jj0hns0n** [comment]
Sorry dude, thats a dropped ball I have to take the blame for. Its done. Cya there
