### ISSUE TITLE
Sort the property names before displaying them in the feature inspector box.

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola#367]
When using the Inspector's Inspect Features tool, the order of fields in the pop-up box randomly changes such that a quick visual comparison as the mouse is moved around becomes difficult. Even when the mouse is over one place, if there are multiple features from the same layer underneath the cursor it will show a different field order (as shown below):
![inspect_fields](https://user-images.githubusercontent.com/5266205/37662890-ab7478b6-2c1d-11e8-9af6-3c41941edeaa.png)

**Comment by gdey** [comment]
This is because we are not sorting the properties in the js hash here before building up the list elements here.
https://github.com/go-spatial/tegola/blob/master/server/static/js/tegola.js#L180

The fix would be to get the list of property names, sort them, then build out the html in the sorted order.

**Comment by erictheise** [comment]
I only noticed this yesterday, as the layer list has never worked for me on any of my independent projects. I submitted #365 yesterday to remedy that and am going to pester @ARolek today about doing a minor release for the benefit of any of the 40 people who try following along in my demo tonight.

@PetersonGIS, I'd propose that you propose a list of properties to always display in a fixed order at the top; any remaining would be sorted alphabetically on the fly. That's what I did for the seamarks inspector, always displaying `osm_id`, `name`, and `type`, then sorting the others alphabetically.

**Comment by gdey** [comment]
@erictheise I can always push out a minor build if you need it.

**Comment by erictheise** [comment]
@gdey, I can do that too, I'd just rather avoid asking people to install a custom build at a demo/workshop. Unless the demo's about testing a feature only available in the custom build.

**Comment by PetersonGIS** [comment]
@erictheise Good idea. For OSM data I think you're right on with "feature id," "name", and "type" being the first three. Maybe it should search for those, if they exist, put those at the top. Natural Earth generally also has "name" and "featurecla." Custom data will need to be sorted alphabetically throughout I guess (unless they have those key field names of course).

**Comment by erictheise** [comment]
I suppose we could complicate things a bit and allow an `options` override where a user could inject something like `{"fixed": ["osm_id", "name", "type", "featurecla"]}` to specify the fields. Hard to know what fields might be in nonOSM data.

**Comment by gdey** [comment]
This is a debug tool; proof of life tool. Let's not complicate it. I'm okay with having a few (thinking less than 5) predefined hard-coded entries, that are sorted to the top, and the rest is sorted alphabetically. The point of this tool is to get people to generate their own styles and see what the system is offering up. When they create their own style, they can sort and organize the field however they need/want. We don't need to offer then that here.

**Comment by erictheise** [comment]
👍
