### ISSUE TITLE
Setting max zoom for a map

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#375]
My map needs a max  zoom at which it will no longer serve and cache tiles.

I tried setting a max_zoom on all the layers that are a part of the map, but a request to a higher zoom was still responded to with a 200 status, and it generated a tile in the cache.

**Comment by gdey** [comment]
What should the status be? 404 for not found, as there are no layers to encode at that zoom level?

**Comment by pnorman** [comment]
400, same as a request for 0/100/100 or some other invalid tile

**Comment by ARolek** [comment]
Another detail to consider with this request is sniffing the `max_zoom` of each layer compared to a map with `max_zoom` set. Should we error on startup or just ignore the layers `max_zoom` if they're greater than the map's `max_zoom`. I lean towards throwing an error on startup.

**Comment by gdey** [comment]
That's is a configuration error, and I think it should error on start up as well.

**Comment by gdey** [comment]
Looking into this, Maps don't have MaxZooms from what I can tell. Neighter the config.Map or the server.Map structs have any concept of MaxZoom, only the layers of a Map has max zoom. As this is the case, I think what @pnorman suggests makes the most sense. If we were to introduce a max_zoom at the map layer, I agree we should error when any layer is set to be greater then the max_zoom of that map, or greater then the `tegola.MaxZoom`.

**Comment by ear7h** [comment]
I think the response should be 404 for tiles not configured. 404 makes it clear that the requested tile isn't available but is a valid request. 400 implies a client error along the lines of syntax or formatting. 

For the case of `0/100/100`, such a tile cannot exist according to the slippy tiles spec. On the other hand, the zoom configurations of maps are defined by the sysadmin and may be subject to change.
