### ISSUE TITLE
Fuzzing wkb encoding causes out of memory errors

### ISSUE THREAD

**Issue by chebizarro** [go-spatial/tegola#384]
Fuzzing geom/encoding/wkb (as per #53) reveals a potential bug with several decode functions. I have attached the relevant test output - [010c1c076fce1acae227d578d230bd713dd44528.txt](https://github.com/go-spatial/tegola/files/1864454/010c1c076fce1acae227d578d230bd713dd44528.txt)

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L155

In this case, the out of memory error occurs when the Collection function reads the number of items [num](https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L151) from the WKB byte stream. In this case it is because of a fuzzed value. When thinking of how to sanitize the input I initially thought it might be sufficient to check it was within a sane range. As far as I can tell, however, there is no documented upper limit for the number of Points in a given geometry (Polygons, Collections etc) in WKB other than math.MaxUint32 (4294967295). 

This also affects the other geometry decoding functions that use the value returned from the WKB byte stream to do slice allocation:

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L134

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L120

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L99

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L78

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L64

https://github.com/go-spatial/tegola/blob/2d90e68580efc38a85e3b6c4ad020a80bf66095a/geom/encoding/wkb/internal/decode/decode.go#L41

**Comment by pnorman** [comment]
> As far as I can tell, however, there is no documented upper limit for the number of Points in a given geometry (Polygons, Collections etc) in WKB other than math.MaxUint32 (4294967295).

I think you hit some practical limits based on the max size of a postgres value

**Comment by gdey** [comment]
Well, we should not panic in either case, the system should return an error, something to effect that the geometry is too big to decode. Thank you for the report and the fuzzing.

**Comment by chebizarro** [comment]
No problem, I looked at how GDAL handles the problem and being written in C/C++ it simply checks for a null return value when calling calloc. Such an option isn't, afaik, available in go - https://github.com/golang/go/issues/16843 - and some of the workarounds suggested are probably unnecessarily complicated (checking heap size, using mmap etc). The simplest solution would be to set arbitrary, memory safe limits and return an error if they are exceeded. I'd be happy to provide a patch if there is agreement that this is the direction to take and what those limits should be. Unfortunately, the WKB specification leaves this wide open.

**Comment by gdey** [comment]
I need to research and think about this. I think the setting a limit isn't much of an option because you have to track the size of all the pieces since you can have an OOM, inside of a deeply nested multipolygon, or collection.
