### ISSUE TITLE
Point of Interest (POI) layer from OSM data 

### ISSUE THREAD

**Issue by peldhose** [go-spatial/tegola#392]
Hi , 
Actually POI data is there with OSM data i think .So is there anyway to show POI layer using tegola ?

**Comment by PetersonGIS** [comment]
We use a table called amenity_points in our tegola-osm implementation that you may want to take a look at as an example of how POI can be filtered from OSM data and used in Tegola: https://github.com/go-spatial/tegola-osm#amenity_points.

**Comment by pnorman** [comment]
In general any Mapnik-based vector tile layer can reasonably easily turned into a Tegola layer definition. They're both SQL, just slightly different keywords and processing.

**Comment by ARolek** [comment]
I'm going to close this issue as there is not continued discussion on it. @peldhose feel free to reopen it if you have additional questions.
