### ISSUE TITLE
Many small vertical polygons in the CleanGeometry output

### ISSUE THREAD

**Issue by jasonsurratt** [go-spatial/tegola#396]
While benchmarking the `CleanGeometry` function I came across a situation where the cleaned/cropped geometry contains many small vertical polygons.

![image](https://user-images.githubusercontent.com/1638013/38567684-1057521c-3ca4-11e8-8769-22c8f2459916.png)

The exact test to recreate the situation can be found here:

https://github.com/jasonsurratt/tegola/commit/ed02e0dda35c96d2464a1bc4b11540c6b0ebacd5

To run the test:

```
cd maths/validate
go test --bench BenchmarkMakeValidCanada 
```

After running the test a GeoJSON output is created that contains both the original polygon and cropped version in the `tegola/maths/validate/testoutput` directory.

I expect an output that looks more like this:

![canadacrop](https://user-images.githubusercontent.com/1638013/38567735-284d9e9e-3ca4-11e8-8fca-8272ba2738b3.jpg)

**Comment by jasonsurratt** [comment]
This may be a function of the Canada polygon + the cleaning function, or possibly the way I'm calling it. Dunno. After trying a dozen or so arbitrary bounding boxes I could not find a situation where it would give the expected output.

For reference, I found this smaller bounding box towards the southern border of Canada that may be easier to debug.

```
	ext := geom.NewExtent(
		[2]float64{-12000000,  6000000},
		[2]float64{-13000000,  7000000},
	);
```

![canadacrop-tegola4](https://user-images.githubusercontent.com/1638013/38568836-ed4f636a-3ca6-11e8-8995-33e8c5cc0d4e.jpg)

**Comment by gdey** [comment]
This is not going to be an issue with the new aglo in geom.
