### ISSUE TITLE
Error in validate.CleanGeometry on fractional coordinates

### ISSUE THREAD

**Issue by jasonsurratt** [go-spatial/tegola#398]
The test case for this can be found [here](https://github.com/jasonsurratt/tegola/blob/intersect_benchmark/maths/validate/validate_test.go#L105). 

To run this:
* checkout the `intersect_benchmark` branch from my [repo](https://github.com/jasonsurratt/tegola)
* `cd tegola/maths/validate`
* Run: `go test -v .`

At this time the test is only printing results and isn't flagging the tests as failures.

Input polygon and extent:
```
		// fractional coordinate
		// if you multiply everything by 10 (remove fraction), then this test case
		// works just fine.
		{
			basic.Polygon { basic.Line {
					basic.Point {.1, 0},
					basic.Point {1, 0},
					basic.Point {0, 1},
			} },
			geom.NewExtent([2]float64{0, 0}, [2]float64{.5, .5}),
		},
```

The winding order and POLYGON vs. MULTIPOLYGON aren't really relevant, the relevant part is (0.05, .5) point vs (0, 0.5) point.

Expected: POLYGON ((0.5 0,0.1 0,**0.05** 0.5,0.5 0.5))
Actual: MULTIPOLYGON (((**0** 0.5,0.1 0,0.5 0,0.5 0.5)))

**Comment by ARolek** [comment]
@jasonsurratt I think this issue better fits in the `geom` package now. Moving it over.
