### ISSUE TITLE
New environment variable support breaks dict.Map parsing 

### ISSUE THREAD

**Issue by ear7h** [go-spatial/tegola#403]
# The problem
One of the constraints placed by the new environment variable support is that the environment variables have to be in strings. As in: 
```toml
# register data providers
[[providers]]
...
port = "{POSTGIS_PORT}"
```

However, the expected value is in the `providers` package is `int64`, seen [here](https://github.com/go-spatial/tegola/blob/v0.7.0/provider/postgis/postgis.go#L118):
```go
port := int64(DefaultPort)
if port, err = c.Int64(ConfigKeyPort, &port); err != nil {
	return nil, err
}
```
As far as the config is concerned, it is a `map[string]interface{}` seen [here](https://github.com/go-spatial/tegola/blob/v0.7.0/config/config.go#L32):
```go
// Config represents a tegola config file.
type Config struct {
	...
	// Map of providers.
	Providers []map[string]interface{}
	...
}
```
# Potential solutions

### 1) Revert to old strategy
Revert to doing `(regexp.Regexp).Replace` before TOML parsing

### 2) Create defined types for all configurable packages
For the providers, this would entail making a `type config.ProviderConfig struct` and so on for the other parts of the codebase that rely on `dict` for their configuration

### 3) Add string to numeric conversions to the `dict.Map` member functions
This is the easiest approach at solving the problem but leaves two parts of the code base doing the same thing (`config/env` also parses the env strings to numeric types).

**Comment by ear7h** [comment]
### 4) Add ambiguous `env.Type`
`env.Type` would would have helper methods for conversion to a primitive type

**Comment by gdey** [comment]
I think it should be called `Interface` i.e. `env.Interface`
