### ISSUE TITLE
BBox not working for Bonn?

### ISSUE THREAD

**Issue by ani82** [go-spatial/tegola#405]
Hi,

I was trying out tegola and had already some OSM data for Germany and in particular Cologne Bonn loaded into Postgis. 

When I try to get a map display for Cologne, I don't get any output. During debugging it turns out that the generated bounding box is not matching the map tile. The data in the table is SRID=4326 and is converted to avoid any additional source of error:

`SELECT gid, ST_AsBinary(ST_Transform(way, 3857)) AS geom, name, "natural" FROM planet_osm_polygon WHERE way && ST_MakeEnvelope(5.674608542073286e+06,684952.2103681198,5.679653385939406e+06,679907.3665020004,3857) and "natural" is not null`

and the config looks like

`[[providers.layers]]
	name = "natural"
	sql = "SELECT gid, ST_AsBinary(ST_Transform(way, 3857)) AS geom, name, \"natural\" FROM planet_osm_polygon WHERE way && !BBOX! and \"natural\" is not null"`

and

`name = "germany"                              # used in the URL to reference this map (/maps/:map_name)
center = [50.986099, 6.965332, 5.0]
bounds = [3.581543, 55.213219, 15.227051, 47.059016]`

`[[maps.layers]]
	name = "natural"
	provider_layer = "postgis.natural"
	min_zoom = 1
	max_zoom = 18`

It seems like the boundary of the slippy map is offset from the tile itself, so that both don't share a common area? I am continuing to debug, but any conformation that BBoxes are still working fine for Europe would be great. Thanks!

**Comment by erictheise** [comment]
@ani82, I routinely use Geofabrik extracts of Italy & all of Europe with v0.6.3 and haven't seen any BBOX issues. But I load my data in 3857 and am not transforming on the fly.

* Are you running a release version or building from the v0.7.0 branch?
* When you say "try to get a map display", do you mean at the root level of the Tegola server itself or by hitting the API?
* Do you get errors in the Tegola log or in your JavaScript console?

**Comment by ARolek** [comment]
@ani82 what I believe is going on here is a mis match of SRIDs. Your data is in 4326 but tegola does not know this. You're converting the data to 3857 on the way out of the database, but tegola is sending in the bounding box query in as 3857. To remedy this you have two options: 

- convert the data to 3857 in the database (most performant)
- tell tegola the data is in 4326 so it will submit the bounding box query in 4326 and convert the geometries to 3857 on the way out. This is less performant but a simple change in you [provider_layers](http://tegola.io/documentation/configuration/#provider-layers) config. An example of your config modified:

```toml
[[providers.layers]] 
name = "natural" 
srid = 4326
sql = "SELECT gid, ST_AsBinary(way) AS geom, name, \"natural\" FROM planet_osm_polygon WHERE way && !BBOX! AND \"natural\" IS NOT null"
```

**Comment by ARolek** [comment]
@ani82 did you have a chance to try out my suggestion?

**Comment by ani82** [comment]
Well, I have just been able to try it. I did a select into a new table:

`create table public.roads as 
SELECT gid, st_setsrid(st_transform(geom, 3857), 3857)::Geometry(Linestring, 3857) AS geom, name, class FROM network WHERE geom is not null`

and checked it with QGIS: Geometry is correctly listed as a Linestring column in the schema metadata.
However, after restart of the server, I am still getting the same errors as I was starting with tegola:

> 2018-05-18 18:37:15 [INFO] handle_map_style.go:138: unable to infer geometry type for providerLayerName: roads. style definition not generated

The part of the confug looks like this:

`	[[providers.layers]]
	name = "roads"
	srid = 3857                      # will be encoded as the layer name in the tile
	tablename = "public.roads"`

Without debugging your completely SQl parser, I don't really know what the problem is. In PostGIS it seems to work, in QGIS as well. Maybe you have any idea?

**Comment by ani82** [comment]
![image](https://user-images.githubusercontent.com/5342170/40252362-72bd8376-5adc-11e8-93e8-0c7fa5a0e753.png)

**Comment by ani82** [comment]
postgis_full_version
POSTGIS="2.3.0 r15146" GEOS="3.5.0-CAPI-1.9.0 4392" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.3.0dev, released 2017/99/99" LIBXML="2.9.1" TOPOLOGY RASTER

This is the Postgis version. Tried it on both Google Cloud SQL (this one) and on another Postgis server with 2.4

**Comment by ARolek** [comment]
@ani82 if tegola can't infer the geometry type, it wont show up in the viewer since it can't auto generate a style, but it will still be encoded in the vector tile. Try adding the layer in your carto and see if it shows up.

**Comment by ani82** [comment]
I did so. Even then, the envelope is far off. 
the OL starts with a center of  (Cologne/Bonn, in 3857)
`
          center: [761654,6633974], //coordinates the map will center on initially
          zoom: 2
`


The debug statements are:

`
    2018/05/18 21:31:11 postgis.go:370: SQL_DEBUG:EXECUTE_SQL for layer (roads): SELECT "gid", ST_AsBinary("geom") AS "geom", "name", "class" FROM public.roads WHERE "geom" && ST_MakeEnvelope(-2.019405137390625e+07,-9.862211136093749e+06,-9.86221113609375e+06,-2.0194051373906247e+07,3857)
2018/05/18 21:39:31 postgis.go:370: SQL_DEBUG:EXECUTE_SQL for layer (roads): SELECT "gid", ST_AsBinary("geom") AS "geom", "name", "class" FROM public.roads WHERE "geom" && ST_MakeEnvelope(-2.019405137390625e+07,2.019405137390625e+07,-9.86221113609375e+06,9.86221113609375e+06,3857)
2018/05/18 21:39:31 postgis.go:370: SQL_DEBUG:EXECUTE_SQL for layer (roads): SELECT "gid", ST_AsBinary("geom") AS "geom", "name", "class" FROM public.roads WHERE "geom" && ST_MakeEnvelope(9.862211136093749e+06,2.019405137390625e+07,2.0194051373906247e+07,9.86221113609375e+06,3857)
`


Seems like the generated envelope is not matching the coordinates requested. Could it be a sign error for the latitude in the code (yours/mine)?

**Comment by ARolek** [comment]
@ani82 can you paste your entire config in here (less any database credentials) so I can take a look at it? Also is your data from https://download.geofabrik.de/? And lastly, what tool did you use to get it into PostGIS (i.e. imposm3)?

**Comment by ani82** [comment]
@ARolek, I used data from geofabrik and imposm3 for importing. As said, the maps are rendering fine in QGIS or with mapnik or tilestache - therefore, I do not assume an import error. Nevertheless, it would be decent to get the huge performance improvements assumed to be with a Go implementation ;-)

The table "public.roads" contains a transformed version of the imported table. Origin was 4326 and transformation was done to 3857 (cross checked by displaying with this projection in QGIS)

Config (completely strapped for debugging, no unneeded settings anymore):

    [webserver]
	port = ":8080"              # port to bind the web server to. defaults ":8080"

	[cache]                     # configure a tile cache
	type = "file"               # a file cache will cache to the local file system
	basepath = "/tmp/tegola"    # where to write the file cache

	# register data providers
	[[providers]]
	name = "prod_postgis"   # provider name is referenced from map layers (required)
	type = "postgis"                    # the type of data provider. currently only supports postgis (required)
	host = "127.0.0.1"    # postgis database host (required)
	port = 5432                         # postgis database port (required)
	database = "prod"       # postgis database name (required)
	user = "user"             # postgis database user (required)
	password = "pass"     # postgis database password (required)
	srid = 3857                         # The default srid for this provider. Defaults to WebMercator (3857) (optional)
	max_connections = 100               # The max connections to maintain in the connection pool. Default is 100. (optional)

		[[providers.layers]]
		name = "roads"
		srid = 3857                      # will be encoded as the layer name in the tile
		tablename = "public.roads"

	# maps are made up of layers
	[[maps]]
	name = "germany"                              # used in the URL to reference this map (/maps/:map_name)
	center = [6633974.0,761654.0, 5.0]


		[[maps.layers]]
		name = "roads"
		provider_layer = "prod_postgis.roads"
		min_zoom = 1
		max_zoom = 18

**Comment by ARolek** [comment]
@ani82 everything looks fine with your config as far as I can tell. You mentioned using Open Layers for the renderer. Have you tried using Mapbox GL? I believe they might use a slightly different zoom strategy where their zooms are off by 1 according to each other. This might be the problem. Also is there anyway you can post a screen shot so I can take a look at what you're seeing and what your expecting?

**Comment by ani82** [comment]
Hi @ARolek 
I cannot find the error in the available timeframe. According to others it must work, therefore, let us close this thread as cannot reproduce. 

Thanks for your help!

**Comment by ani82** [comment]
@ARolek 
I checked the SRIDs and could finally make the debug SQL return non-empty results. That means the intersection of table geometry and bounding box are non-empty.

However, the resulting tiles are all broken with the same short content:

`
	roads( x`

What are the mechanics after the postgis provider returned non-empty geometries? Any conversion? Where could it break finally? All geoms and configs are SRID=3857 to avoid any configuration issues.

p.s.: Why aren't you using ST_asMVT() in postgis 2.4? Would it be worth to have another postgis provider here?

**Comment by ani82** [comment]
@ARolek 
Good news: We were able to isolate the problem. The problem occurs when you use a user who wasnt granted read permissions onto the table or view. Then Tegola renders empty tiles (coming from empty responses) and does not consider the database error thrown.

**Comment by ARolek** [comment]
@ani82 I was thinking about your comment and it sounds like you found a bug. I'm going to open another issue for it so we can get it properly addressed
