### ISSUE TITLE
Support ssl for Postgis connection

### ISSUE THREAD

**Issue by ear7h** [go-spatial/tegola#426]
Running tegola against a `postgres` db which requires ssl yields the following error:
```
tegola@tegola-osm:~/repos/tegola-osm$ tegola serve --config=tegola.toml
2018-05-30 18:10:59 [INFO] config.go:191: loading local config (tegola.toml)
# This Tegola configuration file reads environment variables for sensitive and installation-specific set2018/05/30 18:10:59 root.go:74: Failed while creating connection pool: FATAL: SSL connection is required. Please specify SSL options and retry. (SQLSTATE 28000)
```

I was able to get it running by modifying `provider/postgis/postgis.go` as follows:
```go
p := Provider{
	srid: uint64(srid),
	config: pgx.ConnPoolConfig{
		ConnConfig: pgx.ConnConfig{
			Host:     host,
			Port:     uint16(port),
			Database: db,
			User:     user,
			Password: password,
			TLSConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		},
		MaxConnections: int(maxcon),
	},
}
```

Also of interest, is this error message ecountered during the process of b-lining to a working version.
```
tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

**Comment by nickelbob** [comment]
@ear7h - just to be clear about the expectations here, what options from [the config type](https://godoc.org/crypto/tls#Config) should be configurable? Seems like we at least need ServerName and  InsecureSkipVerify - is that good enough?

**Comment by ear7h** [comment]
@nickelbob I think the options should match that of postgres (`disable`, `prefer`, `require`, etc.). You can use `pgx`'s (unexported) implementation as a guide [here](https://github.com/jackc/pgx/blob/master/conn.go#L962).
