### ISSUE TITLE
in cache/file.go, defer f.Close causing os.Rename to fail in Set method

### ISSUE THREAD

**Issue by TNT0305** [go-spatial/tegola#435]
https://github.com/go-spatial/tegola/blob/9a981d4e900144d0be2d08bf93d4f653e93b4cdd/cache/file/file.go#L126

On line 126 in file.go, the "defer f.Close" is keeping the file open until return.  With the file still open, the os.Rename fails, completely negating the benefits of caching (that is, the correct file is not present in the directory when the cache tries to fetch it and it tries to generate it).

I know Go can do stacked defers with named return values; but, as we might be returning before the rename with an error, I'm not sure how to make that f.Write error (ln 131) take precedence over the defer'd rename return value.  In short, unfortunately, we have to remove the defer and explicitly write the close in both locations as shown here:

	// defer f.Close()

	//	copy the contents
	_, err = f.Write(val)
	if err != nil {
		f.Close() // added because defer'd close inhibits rename
		return err
	}
	f.Close() // added because defer'd close inhibits rename

	//	move the temp file to the destination
	return os.Rename(tmpPath, destPath)

I'm playing with this on Win10 64 bit, running in vs code with the delve debugger.

**Comment by ARolek** [comment]
@TNT0305 great catch! I think this might be related to #422. I will put together a fix shortly.

**Comment by ARolek** [comment]
This has been fixed in the v0.7.0 branch.

**Comment by TNT0305** [comment]
Fantastic!  

On an unrelated note, is there a how-to somewhere on setting up tegola to run under IIS?  I've been looking at HttpPlatformHandler but have, thus far, been unable to make it work.  Besides getting it to start at all, I think I'll probably need to set an environment variable or something for the port tegola uses.  (I just thought I'd asked before I continued to bang my head on the wall)

Thanks!

**Comment by ARolek** [comment]
@TNT0305 so we're mainly building on OSX / Linux but we're looking for some help on Windows best practices. I know @PetersonGIS runs tegola on windows for local carto work. For her use case she does not need to leverage IIS at all. When she runs tegola it binds to the configured port and can start serving tiles. 

Are you looking at using IIS as a proxy server to tegola?

**Comment by TNT0305** [comment]
Correct.  I'm able to run it on windows as its own server just fine (binding to whatever port in the toml).  As we're running a windows stack, I'd like to slot this in under IIS (mainly for lifecycle management, but also for the port 80 binding that IIS is already using for everything else).

Once I figure out the best way to do it, I'll post back here for posterity, though I suspect I *might* need to reach into the tegola code a bit to have it use a port from an environment variable (not a big deal, but a change; so, maybe "port from environment variable" might be something that could be added to 0.7.0?)

**Comment by ARolek** [comment]
@TNT0305 v0.7.0 has environment var support in the config. use the following syntax:

```toml
[webserver]
port = "{$WEBSERVER_PORT}"
```

the `$WEBSERVER_PORT is whatever you name your environment var.

**Comment by TNT0305** [comment]
Ah, fantastic!  Thanks!

Also, (and sorry for just tacking on things in this one thread...I think I'm doing this wrong), I'm trying the seeg command on 0.7 and it doesn't generate any files.  It just lists the zoom levels and stops...here's the output:

./tegola cache seed --bounds "-76,38,-74,40" --min_zoom 4 --max_zoom 10
2018-06-26 13:09:49 [INFO] config.go:163: loading local config (config.toml)
2018-06-26 13:09:49 [INFO] cache.go:111: zoom list: [4 5 6 7 8 9 10]
2018-06-26 13:09:49 [INFO] provider.go:96: cleaning up providers

When I ran it on the master branch, that command worked and my cache directory was populated.  I was about to run it through the debugger to see what's up, but other work stuff popped up.  :(  But, I'll investigate shortly (unless its a "still working on it for 0.7" kind of thing)

**Comment by ARolek** [comment]
@TNT0305 hmm, it should be working on v0.7.0 but that cache seed command did go through a refactor. I would open up a new issue and ping @ear7h as he was the one that most recently worked on that piece. 

Thanks for testing v0.7.0. We're working on getting that released so any and all testing is appreciated.

**Comment by TNT0305** [comment]
You're welcome!  I'll see what I can see in the debugger before posting the issue (I always prefer to include the solution when I can...moreover, it might be me being stupid!)

On the environment variable thing, I still have not gotten that working.  I'm running it from the vscode powershell command line and have set 

$Env:TEGOLA_PORT=8123 

(which is, apparently, how you do that in powershell).  Then, in the TOML, I've tried various permutations of:

port = ":{TEGOLA_PORT}"
port = "{TEGOLA_PORT}"
port = "{$TEGOLA_PORT}"

etc...and it always comes back with something like:

2018-06-26 13:28:06 [ERROR] server.go:78: listen tcp: address {TEGOLA_PORT}: missing port in address
2018-06-26 13:28:08 [INFO] provider.go:96: cleaning up providers

I'll keep looking as I think this one is probably me.

**Comment by ARolek** [comment]
whoops, I mistyped. The $ should be outside the braces. Redo: 

```toml
[webserver]
port = "${WEBSERVER_PORT}"
```

**Comment by erictheise** [comment]
@TNT0305, I've used

`port = ":${TEGOLA_PORT}"`

one of the permutation you've missed.

**Comment by TNT0305** [comment]
Yup, that got it.  Thanks!

**Comment by TNT0305** [comment]
I found the issue in the seeding...it had to do with the order of the bounds parameters.  I will post it as a separate issue and link ear7h.

**Comment by ARolek** [comment]
actually yep @erictheise is the correct one. I forgot the `:`
