### ISSUE TITLE
cache/s3: set proper MIME type

### ISSUE THREAD

**Issue by stvno** [go-spatial/tegola#459]
I noticed that the S3 cache doesn't add a MIME type to the files it uploads. Apparently there is an official MIME type for mapbox vector tiles: https://www.iana.org/assignments/media-types/application/vnd.mapbox-vector-tile 
Shouldn't tegola use that and also add it to the cached files?

**Comment by ARolek** [comment]
@stvno absolutely. Should be a simple implementation and this has value if you're going to fill your cache and serve from it rather than have tegola serve. You can send in a PR if you have a chance to get to it before we do.

**Comment by stvno** [comment]
I never tested it with tegola running from cache and I discovered that Tegola will always serve as 
application/x-protobuf
https://github.com/go-spatial/tegola/blob/master/server/middleware_tile_cache.go#L74

**Comment by ARolek** [comment]
@stvno correct. This should be changed to `application/vnd.mapbox-vector-tile`. I will open an issue for it.
