### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by olt** [go-spatial/tegola#463]
I did some first tests with Tegola and I wanted to find out how it performs and if there are any low hanging fruits.

I used Go's pprof profiler (#462) on a three layer config of OSM buildings, roads, and landuse polygons. Most of the time is spent in Go's `runtime` package which is the result of heavy use of goroutines and creating a lot of objects (which the GC has to handle).

I found that makevalid code creates goroutines for low level operations. Goroutines and channels are cheap, but not free. My gut feeling tells me that parallelism should be applied much higher in the stack (say on `layer` level) if at all (all vector tile requests are handled concurrently already).

https://github.com/go-spatial/tegola/blob/9a981d4e900144d0be2d08bf93d4f653e93b4cdd/maths/makevalid/plyg/ring.go#L923
https://github.com/go-spatial/tegola/blob/9a981d4e900144d0be2d08bf93d4f653e93b4cdd/maths/makevalid/main.go#L112

I removed both worker and request times dropped from 2.45s to 2.1s for one level 14 example tile (no cache, ~280k PBF).

Memory allocations is another topic where the performance can be improved. I spent less than an hour and changed a few `make(X)` calls with `make(X, 0, len(pts)` to preallocate slices. This already dropped the allocations from BenchmarkMakeValid5PolyC-4   37983 allocs/op to 31983 allocs/op. This should reduce pressure on Go's garbage collector and increase performance.
There is more room for improvements. 

makevalid handling is still the largest block where Tegloa spends its time. I wonder if this can be improved by calling it only on complex geometries?

My actual question:

- Are you aware of these issues?
- Are you actively working on this?
- Do you accept PR for such optimizations (or would this collide with work you are doing on this code)?

**Comment by gdey** [comment]
Hey, thanks for looking into this. I'm currently on a major rewrite and simplification of the code, at the geom repo, which will replace this part. I haven't pushed the code yet but would love it if you would want to take a look. I'll try and push it up to a branch by the end of the day, and tag you on it.

**Comment by ARolek** [comment]
@olt thanks for the research! As @gdey mentioned he's currently wrapping up a major refactor to the geometry processing piece of tegola. We're moving all the geo processing methods to a separate repo called [geom](https://github.com/go-spatial/geom) so it can grow and improve independent of tegola. To answer your questions:

>Are you aware of these issues?

Yes. MakeValid is a complex task and something that we have been working on improving for well over a year. The first cut was a huge amount of research and learning, but now the follow up refactor is nearing complete. 

> Are you actively working on this?

Yes. As @gdey mentioned, he will be pushing up a branch to the `geom` package shortly. Having an extra set of eyes on it would be greatly appreciated.

>Do you accept PR for such optimizations (or would this collide with work you are doing on this code)?

Absolutely. In addition to being careful with go routines and pre allocating slices their is also an outstanding issue with the [Go runtime no cleaning up large arrays](https://github.com/golang/go/issues/14045). We don't have a great solution for this yet. 

The better place to continue the conversation will be on the [geom](https://github.com/go-spatial/geom) package. Ultimately we want the `geom` package to be able to replace the geos dependency in imposm (which we all use and love btw). Not that it has to, but be able to. ;-)

**Comment by olt** [comment]
Cool, I'l be watching the geom repo. Feel free to @ me. 

> outstanding issue with the Go runtime no cleaning up large arrays. We don't have a great solution for this yet.

I don't think this applies to Tegola as slices shouldn't hit multiple megabytes?! And even if, the memory still gets reused, but just no immediately. That's how I understand this issue.

**Comment by ARolek** [comment]
It depends on the user's config. If fine grained data is configured to be brought in at coarse zooms then large geoms will be decode from wkb to large slices. We have hit this issue before during seeding jobs which is why I note it. Generally if a config is properly setup then it should not happen.

**Comment by olt** [comment]
I'm closing this. The geom package is the place for further improvments: https://github.com/go-spatial/geom/pull/20
