### ISSUE TITLE
Provide test data download/instructions

### ISSUE THREAD

**Issue by olt** [go-spatial/tegola#464]
I try to run the PostGIS tests but I can't find any information on how to setup the test database.

The Travis script downloads data from https://s3-us-west-1.amazonaws.com/tegola-test-data/tegola-postgis-test-data.backup but this fails (404).

**Comment by ARolek** [comment]
@olt this has changed in the v0.7.0 branch. The test data now lives at: https://github.com/go-spatial/tegola-testdata. You can see the updated ci script [here](https://github.com/go-spatial/tegola/blob/v0.7.0/ci/config_postgis.sh).

**Comment by olt** [comment]
OK, got it. All development happens on v0.7.0 (should probably have been named v0.7.x to avoid mixup with the version tags) and master is stable.

**Comment by ARolek** [comment]
I like the idea of using v0.7.x moving forward. I will implement this for the v0.8.x release cycle.
