### ISSUE TITLE
Document how to point at your own s3-compatible API

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#474]
A number of software packages offer S3-compatible block store APIs. https://github.com/go-spatial/tegola/blob/9c523ad35e1e6ce3a06ca09e580518e78ac65622/cache/s3/README.md should document how to change the host that is used in order to point at them.

**Comment by pnorman** [comment]
ref. http://docs.ceph.com/docs/mimic/radosgw/s3/ https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html

**Comment by ARolek** [comment]
@pnorman in the v0.7.0 branch their have been some updates to the [s3 package](https://github.com/go-spatial/tegola/blob/v0.7.0/cache/s3/README.md) including the addition of the `endpoint` config param which is used for non AWS deployments. Let me know if you think additional details / configs should be added:

**Comment by ARolek** [comment]
@pnorman if you're still having issues feel free re-opening this issue.

**Comment by pnorman** [comment]
I'm still in the development stage, so I'm not yet using anything other than disk cache.

I'll review the docs when I'm ready to use them.
