### ISSUE TITLE
Seeding with bounds does nothing

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#482]
When I run `~/go/src/github.com/go-spatial/tegola/cmd/tegola/tegola cache seed --min_zoom 0 --max_zoom 12 --bounds "-123.37,49.01,-122.66,49.38" --map bolder` tegola exits right away.

This might be related to #437

**Comment by pnorman** [comment]
Ah, the bounds aren't critical here. `~/go/src/github.com/go-spatial/tegola/cmd/tegola/tegola cache seed --min_zoom 0 --max_zoom 6` also exits in a few ms and does nothing to the cache folder

**Comment by ARolek** [comment]
@pnorman please pull the latest version of v0.7.0 as this has been addressed.

**Comment by pnorman** [comment]
Confirmed working
