### ISSUE TITLE
Improve display of tile rendering times

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#484]
When seeding, the log shows stuff like

```
2018-08-03 04:38:53 [INFO] cache.go:251: seeding map (bolder) tile (4/15/15) took: 546.098571ms
2018-08-03 04:38:53 [INFO] cache.go:251: seeding map (bolder) tile (4/14/8) took: 4.656699255s
2018-08-03 04:39:06 [INFO] cache.go:251: seeding map (bolder) tile (4/2/5) took: 54.470062566s
```

There are two problems with this

1. The times are shown with a nano-second precision. This is excessive and makes it harder to read. Times to the nearest ms or 0.1 ms are accurate enough

2. The times are in different units, which makes it hard to parse. For many applications I'd like to capture the data and do histograms of tile generation time so I know if a change is an improvement or not. This is easier with consistent units. Even when viewing directly, consistent units makes it easier to see at a glance when a time is larger.

**Comment by ARolek** [comment]
@pnorman the times are formatted per Go's [time.Duration](https://golang.org/pkg/time/#Duration) String() format. I can understand the need for consistency when parsing logs though. We could change this to just Seconds and truncate the decimal to 2 places.

**Comment by pnorman** [comment]
I'd keep ms resolution. Generation times in the 100ms range are common, so 10ms resolution is a bit low.

**Comment by olt** [comment]
@ARolek I left a comment in https://github.com/go-spatial/tegola/pull/543 (not sure if you get a notification for comments in merged PRs).
