### ISSUE TITLE
Support for geography type? 

### ISSUE THREAD

**Issue by pmabey** [go-spatial/tegola#485]
Is there support for the Postgis geography type? I've tried to get it working by casting it to a geometry type but so far haven't had any luck. Using the following allows the server to startup but am unable to see the layer in the browser. 

SELECT id,ST_AsBinary(geog::geometry) AS geog FROM public.sites WHERE geog::geometry && !BBOX!

**Comment by ARolek** [comment]
@pmabey I believe that the geography type in PostGIS is all in WGS84, so just set the `srid` for the provider table to `4326`. You can find some more info in the docs [here](http://tegola.io/documentation/configuration/#postgis-1). 

I have not tried running tegola against a geography type, so please report back if this works.

**Comment by pmabey** [comment]
Success....had the wrong SRID defined. Fixed it and now am able to successfully pick up a geography type as long as I cast it to a geometry.

**Comment by ARolek** [comment]
@pmabey great. Did you try fetching the geography without the cast by chance?

**Comment by pmabey** [comment]
Yep, but got the following error when launching the server:
2018/08/07 00:14:41 root.go:74: error fetching geometry type for layer (sites): ERROR: function st_geometrytype(geography) does not exist (SQLSTATE 42883)

**Comment by ARolek** [comment]
@pmabey that makes sense. We try to infer the geometry type on startup but that would fail for the geography types. We have a new feature in v0.7.0 (thanks to @olt) that allows you to define the geometry type in the config so tegola wont sniff for the type. This might make it so geography types work.
