### ISSUE TITLE
Labels rendering

### ISSUE THREAD

**Issue by Linolium** [go-spatial/tegola#488]
Hello, i have one question about rendering labels of roads, areas and etc.
I using tegola as tile server and [react-map-gl](https://github.com/uber/react-map-gl) as lib for react application to render it. Assume that I have to attach "glyphs" field and layer with the type equals symbol to the style.json for frontend part of application to display fonts.
I can't understand how i can display my own labels, when i used raster maps render it was very simple (just need to change column`s field or tag to display it ).  In your's [tutorial](http://tegola.io/tutorials/tegola-with-mapbox/) you use openbox styles to display labels. So, how i can render my own data, it's possible with my current stack?

**Comment by erictheise** [comment]
Not sure if this answers your question, @Linolium, but I've had to work out a local fontstack recently myself. I ended up using [genfontgl](https://github.com/sabas/genfontgl), specifying an output location of `glyphs` in my server root, then used `"glyphs": "/glyphs/{fontstack}/{range}.pbf` in my mapbox json style. [node-fontik](https://github.com/mapbox/node-fontnik) might also be applicable in this context but I got to `genfontgl` first.

Hope that helps.

**Comment by ARolek** [comment]
@Linolium it will probably be helpful to look at some of the style sheets in the [tegola-web-demo](https://github.com/go-spatial/tegola-web-demo/tree/master/styles) repo. [here](https://github.com/go-spatial/tegola-web-demo/blob/master/styles/hot-osm.json#L2719) is an example of using a tag to put a label on a line for `transport_lines` and an example of a symbol layer can be found [here](https://github.com/go-spatial/tegola-web-demo/blob/master/styles/hot-osm.json#L2800).

**Comment by Linolium** [comment]
@erictheise @ARolek Thx a lot, i will try something with it soon. I will leave a response about result.

**Comment by Linolium** [comment]
I configured glyphs on client, it works perfectly but i am using mapbox servers to take glyphs and sprites. 
I tried to write my own server for that(kotlin + springboot) but got some problems with protobuf protocol. Where can i take glyphs and sprites servers to deploy it on my VM?

**Comment by ARolek** [comment]
@Linolium have you considered using [github pages](https://pages.github.com/) to host the glyphs and sprites? That's what the [tegola demo](https://demo.tegola.io) is doing.

**Comment by Linolium** [comment]
@ARolek glyphs requests currently don't working in demo, all requests have 404 status. I wonder, it's necessary to get glyphs as requests with content type application/x-protobuf or i can get them in different way.

**Comment by ARolek** [comment]
@Linolium everything shows as a 200 on this end (screen shot attached)
<img width="692" alt="screen shot 2018-08-15 at 2 16 57 pm" src="https://user-images.githubusercontent.com/667850/44173830-efe2f580-a095-11e8-90fe-27cfa17ce687.png">

**Comment by Linolium** [comment]
@ARolek maybe it's private? Because i get errors
![image](https://user-images.githubusercontent.com/16257276/44174416-c359c880-a0eb-11e8-82b7-3d2d27ae9062.png)
And when i follow this link i get
![image](https://user-images.githubusercontent.com/16257276/44174490-f9974800-a0eb-11e8-94c5-5f67a35dd2ec.png)

**Comment by Linolium** [comment]
@ARolek argh, i understood, it's because of adblock in chrome, when i turned it off everything worked

**Comment by ARolek** [comment]
@Linolium I wonder why adblocker is blocking GH pages...

**Comment by Linolium** [comment]
@ARolek i dunno, finnaly i did it, everything work fine
![image](https://user-images.githubusercontent.com/16257276/44462580-ad816180-a61d-11e8-86f7-c5f8e35f32c0.png)
I just wrote simple spring-boot application for provide glyphs, fonts and construct routes, thx you a lot for help.
