### ISSUE TITLE
SQL_DEBUG=LAYER_SQL:EXECUTE_SQL no longer prints to terminal

### ISSUE THREAD

**Issue by brianbancroft** [go-spatial/tegola#513]
Hi there, 

`SQL_DEBUG=LAYER_SQL:EXECUTE_SQL` is a fantastic tool for debugging by determining what the problem with the thing I'm doing is, as every time I hit a tile, I come up with a lovely visual indicator such as this:

![image](https://user-images.githubusercontent.com/6225122/45446188-409c3d00-b69a-11e8-95ce-4eb7e4e11766.png)

But starting with the Tegola 7 release, this is no longer something that I can see? Is this intended (and needs to be stripped from the docs), or is it a bug? 

Keep up the good work!

**Comment by ARolek** [comment]
@brianbancroft that env var was named to `TEGOLA_SQL_DEBUG` in v0.7.0. We're prefixing all the tegola specific env vars with `TEGOLA_` now to avoid potential conflicts with other env vars.

**Comment by brianbancroft** [comment]
Cool beans. Closing as this isn't an issue, then!
