### ISSUE TITLE
v0.7.0: Missing permissions on tables/views are not covered by any error message

### ISSUE THREAD

**Issue by ani82** [go-spatial/tegola#523]
Good news: We were able to isolate the problem. The problem occurs when you use a user who wasnt granted read permissions onto the table or view. Then Tegola renders empty tiles (coming from empty responses) and does not consider the database error thrown.

**Expected behavior:** server error 500 via API + error message via STDOUT reg. missing table permissions
**Shown behavior:** HTTP 200 with map or layer name plus empty tile
**Branch:** v0.7.0 using POSTGIS provider

_Originally posted by @ani82 in https://github.com/go-spatial/tegola/issue_comments#issuecomment-426180813_

**Comment by ARolek** [comment]
@ani82 great! thanks for digging into the bug and finding the underlying issue. I will look into capturing this error and reporting it accordingly. I'm surprised the error is not being thrown right now.

**Comment by ARolek** [comment]
This has been addressed in the upcoming release under #538.
