### ISSUE TITLE
Limit tegola serve to given bounding boxes

### ISSUE THREAD

**Issue by bagage** [go-spatial/tegola#525]
The `tegola cache` command supports a `--boundingbox` parameter to generate cache only for given bbox.

However I'd like to define this is the config.toml file instead, because I'm serving tiles only for a single country and thus I have no interest in doing postgres queries outside of it. Ideally, it should work with a polygon instead of bounding box, because France is a multipolygon and I cannot define a single bbox for it.

Is it something planned?

**Comment by ARolek** [comment]
@bagage interesting idea and not something I had thought of. I think this could be accomplished outside of tegola in a few ways though:

- If you prune your PostGIS dataset to only include data form a certain area (i.e. France) then requests for data outside the target area will return no features and be very quick to process. 
- If you have the target polygon in your database you could add a filter to your queries with an [ST_Intersects()](https://postgis.net/docs/ST_Intersects.html).
- You could limit the area the user can navigate the map using a bounds restriction. [Example with mapbox GL](https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/). 

Let me know if any of those options would work or not work for your use case.

**Comment by bagage** [comment]
Hey @ARolek, thanks for the suggestions!

- Your first suggestion is correct, however they are 2 drawbacks: first tegola do the query even if no data is returned. In my case the query is not totally trivial, so it still takes some ms for nothing. But main problem is that when you cache tiles (using `file cache`), an **empty tile file is not an empty file**. An empty tile is around 4kb. Multiplied by the whole world and up to zoom level 13, that consumes some storage for nothing
- That's an interesting idea, I'll probably do that :). I believe the overhead will be minor.
- This is not possible in my case but indeed it could be a solution.

**Comment by ARolek** [comment]
All of the suggestions will still produce the empty tile, though I think the empty tile in the cache is probably better than querying the database over and over, though this could be changed in the future.
