### ISSUE TITLE
Slow performance on low zoom tiles

### ISSUE THREAD

**Issue by russss** [go-spatial/tegola#526]
I'm trying to run tegola on a non-trivial, but still relatively small, dataset which is approximately 10GB in PostGIS (the DB behind [OpenInfraMap](openinframap.org)). Tegola is taking a really long time to render low-zoom tiles - in excess of 5 minutes for the single tile 0/0/0 - plus it's using over 12GB of RAM and getting OOM-killed.

For comparison I can preseed 6 zoom levels in Mapnik in less than 2 minutes on this machine. I'm using tegola from git master built with go 1.11.1.

I'm not sure if I'm doing something obviously wrong here - I have min-zoom set on a number of the denser layers but this doesn't seem to affect the tile generation. Should I be somehow filtering this data in SQL?

I'm testing this using `tegola cache --bounds="-180,-85.0511,180,85.0511" --concurrency 1` and it's using up the whole 600% CPU, while Postgres is idle waiting for the client to receive data.

Pprof data below, for what it's worth:
```
(pprof) top10
Showing nodes accounting for 68.60s, 83.82% of 81.84s total
Dropped 169 nodes (cum <= 0.41s)
Showing top 10 nodes out of 54
      flat  flat%   sum%        cum   cum%
    15.19s 18.56% 18.56%     59.68s 72.92%  github.com/go-spatial/tegola/mvt.(*Layer).AddFeatures
    14.93s 18.24% 36.80%     26.22s 32.04%  runtime.scanobject
    13.42s 16.40% 53.20%     14.97s 18.29%  runtime.findObject
     8.25s 10.08% 63.28%      8.25s 10.08%  runtime.memmove
     3.86s  4.72% 68.00%      3.86s  4.72%  runtime.memclrNoHeapPointers
     3.20s  3.91% 71.91%      4.86s  5.94%  runtime.greyobject
     3.12s  3.81% 75.72%     15.37s 18.78%  runtime.wbBufFlush1
     2.67s  3.26% 78.98%      2.67s  3.26%  runtime.markBits.isMarked (inline)
     2.10s  2.57% 81.55%      2.10s  2.57%  runtime.(*wbBuf).putFast (inline)
     1.86s  2.27% 83.82%      1.96s  2.39%  runtime.heapBitsSetType
```

![profile001](https://user-images.githubusercontent.com/45057/46730068-f39e8d00-cc7e-11e8-9c3d-326838336d03.png)
[pprof.tegola.samples.cpu.002.pb.gz](https://github.com/go-spatial/tegola/files/2464313/pprof.tegola.samples.cpu.002.pb.gz)

**Comment by ARolek** [comment]
@russss thanks for the report and the pprof output. A few things going on here:

- processing time is closely tied to the tegola configuration. For some of the lower zoom levels could you pre simplify the geometries or minimize the dataset / layers at that zoom?
- we're currently working on numerous rendering and processing optimizations in a branch but unfortunately we don't have a hard target date for when that will be done. Once the rendering improvements are in place we're going to focus on a round of performance optimizations. 

If you post some of your config file I can see if there is any low hanging fruit I can see that will help with performance near term.

**Comment by ARolek** [comment]
@russss looking at this graph a bit more I'm wondering if one of the changes I put in the v0.8.x branch for AddFeatures would reduce a lot of the runtime overhead. It's a quick patch you can try. Change:

https://github.com/go-spatial/tegola/blob/master/mvt/layer.go#L145 to: https://github.com/go-spatial/tegola/blob/v0.8.x/mvt/layer.go#L144

You can always return `false` so the function signature does not change.

**Comment by russss** [comment]
> processing time is closely tied to the tegola configuration. For some of the lower zoom levels could you pre simplify the geometries or minimize the dataset / layers at that zoom?

There is definitely more data included here than is necessary, so I guess part of this issue is related to the fact that it's not especially clear how to do this at the moment. Most layers are definitely unnecessary at zoom 0, but I think I would expect the `max_zoom` and `min_zoom` config options to do the zoom level filtering when the tiles are produced, rather than just affecting the json.

I guess the initial fix here involves adding `AND 5 < !ZOOM!` to the SQL (it turns out `!ZOOM!` isn't actually documented either, and that comparison still only works in one direction as per #343). It might also be nice to have a feature in tegola to automatically filter objects by size rather than having to repeatedly embed all that logic into the SQL.

Still, even with the large amount of data here (I reckon probably around a million objects), it seems like 12GB of RAM is a bit excessive, so I guess this is a good pathological test case.

I tried applying that fix as well as applying some zoom level filtering and it is just about working now. It is, however, still using around 3GB of RAM and taking three minutes of CPU time to generate 800KB .pbf files.

**Comment by russss** [comment]
I got it working fine after applying some more zoom filtering, so I'll close this.
