### ISSUE TITLE
add fuzzing to wkb package

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#53]
fuzzing will help us identify any edge case bugs.

**Comment by chebizarro** [comment]
PR #389 adds a Fuzz function for wkb using the go-fuzz package. I'm not quite sure how to approach the mvt package as it uses the protobuf library for decoding/encoding which has already been fuzzed.

**Comment by ARolek** [comment]
@chebizarro I'm going to drop the MVT fuzzing form this issue. We can open a separate issue if we decide MVT needs additional fuzzing attention.

Thanks for your work on this!

**Comment by ARolek** [comment]
the wkb package has moved to github.com/go-spatial/geom and now has a fuzzing.
