### ISSUE TITLE
high number of postgis connections / connection pooling

### ISSUE THREAD

**Issue by stvno** [go-spatial/tegola#532]
I'm running a tegola seeding run where the data comes from three different databases on the same postgresql server. I've configured tegola with `max_connections = 50` and while checking the postgresql performance with pghero it complained about the high number of connections:
```
High Number of Connections

133 connections

Use connection pooling for better performance. PgBouncer is a solid option.
```
So I was wondering why we don't use connection pooling, it seems to me cheaper to not create multiple database connections

**Comment by ARolek** [comment]
@stvno tegola does use connection pooling right now. The high number of connections is due to the pool expanding to that `max_connections` value and keeping the connections open. You can always lower the `max_connections` value which is helpful if you're scaling horizontally.

**Comment by stvno** [comment]
ah ok, thanks for the explanation

**Comment by stvno** [comment]
ah ok, thanks for the explanation
