### ISSUE TITLE
Change server endpoint

### ISSUE THREAD

**Issue by Linolium** [go-spatial/tegola#545]
Hello. Is it possible to change endpoint? For example - from "/" to "/tegola/".

**Comment by ARolek** [comment]
Hmm, not something I have been considering. Can you tell me more about the use case?

**Comment by Linolium** [comment]
@ARolek For security reasons i need to put all my applications on same domain. I proxy tegola via nginx to context domainname.com/tegola/ , but jsons generated by tegola have urls to root.

**Comment by ARolek** [comment]
@Linolium have you tried using the [hostname](http://tegola.io/documentation/configuration/#webserver) config? I just gave it a test and it could work for your situation. It looks like if a port is included in the request that the URL will be ill formatted, but if you add `hostname = domain.com/tegola` the JSON will use this as the hostname.

**Comment by Linolium** [comment]
@ARolek It works perfectly, thank you
