### ISSUE TITLE
Logging/Output is very verbose

### ISSUE THREAD

**Issue by wfortin136** [go-spatial/tegola#549]
After the deploy of the new image to version 0.8.0, docker output is super verbose compared to 0.7.0. New logs are constantly spitting these statements:
![image](https://user-images.githubusercontent.com/10665247/47939015-d6db2b00-deb3-11e8-834b-5de4a28e0431.png)

I reverted to 0.7.0 to so the output wouldn't eat up disk space and crash my container.

**Comment by ARolek** [comment]
Thanks for the report. Looks like some left over log statements got missed. I will fix ASAP.

**Comment by ARolek** [comment]
A new version of v0.8.0 was pushed this morning. This is now fixed. Thanks for the report.

**Comment by wfortin136** [comment]
Thanks for such a quick turn around!

**Comment by ARolek** [comment]
Thanks for the report! I messed up the merge on that release.
