### ISSUE TITLE
Seed with tile-list documentation is outdated

### ISSUE THREAD

**Issue by tomass** [go-spatial/tegola#551]
Documentation here:
http://tegola.io/documentation/cache-seeding-and-purging/
shows usage with _--tile-list_ which no longer works:
`./tegola cache seed --tile-list="expired_tiles.txt"`

Unclear how to use tile-list now, because following option does not work as well:
`./tegola cache seed tile-list mano_list.txt`
giving error:
`Error: expected purge/seed got () for command name`
(using tegola compiled from latest trunk in github)

**Comment by tomass** [comment]
This assignment in _seed_purge.go_ returns _null_ value:
`cmdName := strings.ToLower(strings.TrimSpace(cmd.CalledAs()))`
If I manualy overwrite it like this:
`cmdName = "seed"`
then seed operation works as expected (this is of course only workaround/test, not a fix).

**Comment by ARolek** [comment]
@tomass thanks for the report. @gdey is looking into this.
