### ISSUE TITLE
Support ST_AsMVT?

### ISSUE THREAD

**Issue by yh371174229** [go-spatial/tegola#554]

**Comment by ARolek** [comment]
Support for PostGIS 3.0 `ST_AsMVT` will be added in tegola v0.12.x. You can track the progress in the PR: https://github.com/go-spatial/tegola/pull/687. Builds artifacts for testing are also in the [GH Actions](https://github.com/go-spatial/tegola/actions?query=workflow%3A%22On+release+publish%22) if you're interested in testing a binary.
