### ISSUE TITLE
Tegola cache's doesn't updated even Cache-Control = "must-revalidate" header is added to configuration file

### ISSUE THREAD

**Issue by capan** [go-spatial/tegola#570]
My configuration file has the **Cache-Control = "must-revalidate"** flag. When I run the server on Windows it renews the changed data immediately. But when I run the server on Linux I see the tiles are not changing.
I suppose this is about Linux folder permissions. I've tried giving all read and write permissions  the created cache folders (octal code 0777) But new created cache files were created with different permissions so I've used umask 000 command so all newly created files are editeble by all user. Though, nothing has changed. 

If anyone has a suggestion on this issue I've very glad to hear it.
Windows Version: 10
Linux: AWS Kali Linux t2.medium
Tegola version : 6.

**Comment by dBitech** [comment]
the Cache-Control header does not instruct tegoa to regenerate it's tiles, but instead sends the cache control header to the client/proxy to tell it it is supposed to ask tegola to serve the tile, either as a new rendering if it does NOT exist within the tegola filesystem cache, or else return it from the configured on disk cache.

**Comment by gdey** [comment]
@capan did @dBitech answer your question? Should I close this issue?

**Comment by capan** [comment]
Hi @gdey ,
You can close the issue. Seeding/purging was the answer I was looking for. I haven't tested yet but testing is not related with this issue. 
Thank you
