### ISSUE TITLE
Generate pbf static tiles from tegola.

### ISSUE THREAD

**Issue by Linolium** [go-spatial/tegola#572]
Good afternoon everyone. I want to ask, is it possible to generate pbf files from tegola cache or tegola itself. I want to get pbf static files to use it in mobile application with offline map (mapbox library + pbf  tiles).

**Comment by Linolium** [comment]
@ARolek thank you for your response. I already generated cache but this files haven't extension, i know that they gzip encoded now, but in previous versions of tegola they had same structure "1", but i want to get 1.pbf for example.

**Comment by Linolium** [comment]
@ARolek when i decoded them and tryed use in my fronend application with mapbox library, it gave me error 'Uncaught Error: Unimplemented type: 7'. Do you know where i can find solution to fix that problem?

**Comment by Linolium** [comment]
@ARolek ah, that's was my mistake with decoding, it's work perfectly, thank you!

**Comment by ARolek** [comment]
@Linolium glad that worked out for you. I would like to make that flow even easier as your use case has come up before. What mobile client side library are you rendering the tiles with?

**Comment by Linolium** [comment]
@ARolek i plan to use [flutter-mapbox-gl](https://github.com/mapbox/flutter-mapbox-gl). If you need some feedback from me, I'll be glad to help you.

**Comment by ARolek** [comment]
@Linolium ok great. Even documenting this flow would be helpful for now. Does the client not work with gzip encoded tiles? Originally tegola did not gzip tiles but it was brought to my attention that gzip is expected. I would assume mapbox-gl is expecting the compressed tiles when stored locally.

**Comment by Linolium** [comment]
@ARolek I have some issues in other application for now, i'll finish them and when i collect some information about mobile flow with mapbox-gl, i'll describe it.
