### ISSUE TITLE
tile_buffer has no effect on resulting vector-tile

### ISSUE THREAD

**Issue by henrythasler** [go-spatial/tegola#574]
### Action

1. apply patch from #573 to branch `v0.9.x` and build from source
2. set `tile_buffer=1000` in `config.toml` for a specific map or globally
3. have linestring-features drawn as wide (60px) line
4. use postgis-backend

### Expected Behavior

`tile_buffer` is applied correctly and wide linestrings are shown w/o clipping

### Observed Behavior

Runway is clipped where it shouldn't:
![image](https://user-images.githubusercontent.com/6277203/52918102-7e5d5b80-32f3-11e9-963a-0eef22d0c5ce.png)

The tile_buffer is applied correctly in the sql-query:

![image](https://user-images.githubusercontent.com/6277203/52918118-d2684000-32f3-11e9-8167-8c1573f0ae30.png)
grey=feature; red=tileborder; green=ST_MakeEnvelope(...) in live sql-statement with 1000px Buffer (drawn with QGIS)

The issue must be AFTER the sql-query. Probably during the clipping/makevalid-stage.

Setting `DefaultTileBuffer` in `tile.go` to `256` solves the issue.

**Comment by ARolek** [comment]
This has been addressed in the v0.9.x branch.
