### ISSUE TITLE
Feature IDs should be signed, not unsigned integers

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#578]
![image](https://user-images.githubusercontent.com/1190866/53545703-31416c80-3adf-11e9-9f14-62c37a74ccd1.png)

osm2pgsql DBs can have negative IDs. This ID is -1427616 + 2^64

**Comment by ARolek** [comment]
@pnorman the MVT spec requires uint64 for feature ids. if you need an int64 I would suggest configuring tegola to encode the tag `feature_id` rather than setting the feature_id. More information can be found in an issue I opened on the spec repo: https://github.com/mapbox/vector-tile-spec/issues/94
