### ISSUE TITLE
Adding remote host

### ISSUE THREAD

**Issue by reyemtm** [go-spatial/tegola#588]
I am trying to add a remote host - managed PostgreSQL db - into "host" and am getting a "too many colons in address" error. I tried both the domain and IP. I am running v0.8.1. If I do not put an "http://" it thinks the host is still the localhost and of course cannot find the database as there is none with those credentials. It is working otherwise with a database on localhost.

**Comment by ARolek** [comment]
Can you post that part of your config file but modify the hostname so that's not exposed? I would like to see what the config looks like that's causing problems.

**Comment by ARolek** [comment]
@reyemtm I'm going to close this issue for now. If you have any additional info you can provide please reopen the issue.
