### ISSUE TITLE
!BBOX! token generates invalid ST_MakeEnvelope

### ISSUE THREAD

**Issue by vetjee** [go-spatial/tegola#589]
### Actual Behavior
The `!BBOX!` token contains coordinates which appear to be wrong.
```
TEGOLA_SQL_DEBUG:EXECUTE_SQL for layer (road): SELECT ST_AsBinary(way), name, osm_id FROM planet_osm_roads WHERE way && ST_MakeEnvelope(567449.3886530882,6.81571782792677e+06,568710.599619618,6.816979038893299e+06,3857)
```

The first and third coordinate seem to be right, however the second and fourth not.

### Expected Behavior

I'd expect the coordinates to be like this:

```
ST_MakeEnvelope(567449.3886530882,6815717.82792677e+06,568710.599619618,6816979.038893299e+06,3857)
```

### Steps to reproduce the issue.
1. Download Geofabrik data.
2. Import to Postgresql
3. Serve with config below.

#### Data used (where to get the data.)
I used a dataset from Geofabrik and imported in Postgresql using osm2pgsql.

#### Config file (sanitized version of the config file used.)
```
[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "utrecht" 
type = "postgis"
host = "localhost"
port = 5432
database = "osm"
user = "tegola"
password = ""
srid = 3857

[[providers.layers]]
name = "road"
geometry_fieldname = "way"
id_fieldname = "osm_id"
sql = "SELECT ST_AsBinary(way) AS wkb_geometry, name, osm_id FROM planet_osm_roads WHERE wkb_geometry && !BBOX!"

[[maps]]
name = "utrecht"

[[maps.layers]]
provider_layer = "utrecht.road"
min_zoom = 0
max_zoom = 20
```

**Comment by ARolek** [comment]
Do you have the z/x/y tile value? that's what's used to calculate the bbox value. With that we can make a test case.

**Comment by vetjee** [comment]
`tile (z: 16, x: 33700, y: 21619)` generates  `ST_MakeEnvelope(569904.9281864072,6.8169503750076955e+06,570535.5336696722,6.81758098049096e+06,3857))`

**Comment by pnorman** [comment]
> I'd expect the coordinates to be like this:

> ``...6815717.82792677e+06...``

This would be wrong, that would give a value of approximately 6.8e12.

> sql = "SELECT ST_AsBinary(way) AS wkb_geometry, name, osm_id FROM planet_osm_roads WHERE wkb_geometry && !BBOX!"

The WHERE clause should be ``WHERE way && !BBOX!``.

**Comment by vetjee** [comment]
@pnorman You are right, changing the query to 
```
SELECT 
   ST_AsBinary(way) AS way, 
   name, 
   osm_id 
FROM 
   planet_osm_roads 
WHERE 
   way && ST_MakeEnvelope(567430.2793960195,6.809583756407738e+06,569952.7013290793,6.812106178340796e+06,3857)
```

Fixed my problems. There is nothing wrong with the !BBOX! token.
