### ISSUE TITLE
cache/redis: add configurable expiration time

### ISSUE THREAD

**Issue by tierpod** [go-spatial/tegola#600]
I see that RedisCache has Expiration field: https://github.com/go-spatial/tegola/blob/master/cache/redis/redis.go#L90

It would be nice to add ability to configure expiration time. I will try to implement it.

```go
func (c *Client) Set(key string, value interface{}, expiration time.Duration) *StatusCmd
```

**Comment by ARolek** [comment]
This has been merged into the v0.10.x branch
