### ISSUE TITLE
just grid, no map

### ISSUE THREAD

**Issue by pacobeending** [go-spatial/tegola#603]
<img width="1344" alt="屏幕快照 2019-05-03 下午4 38 17" src="https://user-images.githubusercontent.com/50231399/57130351-c86ebd00-6dcb-11e9-875d-67ec701c1686.png">

i use imposm3 to import osm data into postgres, but there is just grid, no map.
the config is from https://github.com/go-spatial/tegola-osm/blob/master/tegola.toml
i really have no idea whats wrong in my case, every step looks like right and there is no error warning, does anyone can help me?  thx！！

**Comment by ARolek** [comment]
Did you import the entire planet or just a specific part of the world? If the later, then you may need to position the map over the area of the world the dataset covers.

**Comment by ARolek** [comment]
@pacobeending if you can provide more context I'm happy to keep the conversation going. Closing for now.
