### ISSUE TITLE
Tegola Lambda: "Endpoint request timed out"

### ISSUE THREAD

**Issue by stdmn** [go-spatial/tegola#606]
I've now gone through the [Tegola Lambda](https://github.com/go-spatial/tegola/blob/84cf61f36276ea44546bb45b24f8ba42e7fcf883/cmd/tegola_lambda/README.md) tutorial 3 times, checking to make sure that there were no errors in my implementation. I've tried with both tegola_lambda 0.9x and 0.8x. I know that my config.toml file works because it runs locally.

Each time I finish, after copying the API endpoint with "/capabilities," I receive an "Endpoint request timed out." I've double checked and my implementation correctly includes the maximum (29s) time out length.

One thing I've noticed is that the "Basic Edge Lambda Permissions" under Policy Templates is now called "Basic Lambda@Edge permissions (for CloudFront trigger)," but that seems to be the only significant difference.

Any thoughts?

**Comment by ARolek** [comment]
@stdmn usually you need to prefix the name of the deployment stage to the URL, like `/dev/capabilities`. Have you tried that yet?

**Comment by stdmn** [comment]
Wow. Speedy reply. Yep, for reference, this is what my call looks like: 
`https://[APIAddress].execute-api.us-east-1.amazonaws.com/dev/capabilities`

**Comment by ARolek** [comment]
@stdmn Looks like there's an issue connecting to your database instance so tegola is never running as a webserver. I would suggest checking your security groups and IAM roles to make sure your Lambda function can communicate with your database. Once that's addressed the function might run fine.

**Comment by stdmn** [comment]
Will do. Thanks for the help!

**Comment by ARolek** [comment]
Anytime!
