### ISSUE TITLE
AWS Lambda: global state for database connection caching. 

### ISSUE THREAD

**Issue by paul-pries-weatherlogics** [go-spatial/tegola#609]
Is there a reason why the connection to AWS Lambda must be rebuilt each time as per the tegola lambda readme? I am trying to speed up a web app, and I believe this is a bottleneck. Is there a way the connection can be implemented in order to keep it open?

**Comment by ARolek** [comment]
@paul-pries-weatherlogics could you give me a bit more context? Are you talking about the connection between the web app and tegola lambda or tegola lambda and the database?

**Comment by paul-pries-weatherlogics** [comment]
The tegola_lambda README says that the connection to the database must be rebuilt on each request. (No connection pooling). It's my understanding that if a connection is opened outside of the handler, it remains warm in an AWS lambda container and does not need to be rebuilt, thereby speeding up API calls.

Is there a way to implement the connection outside of the handler in this way, or is there something in the design of the lambda function that prevents this from being done?

**Comment by ARolek** [comment]
Hmm, do you have some documentation you can point to about the connection being persisted outside the handler? I would like to look into this a bit more. 

Regarding the documentation, if the lambda function is still warm the connection pool may be maintained by the lambda runtime. If the lambda function goes cold it will absolutely be killed. One of the slowest parts of using tegola lambda is when it's used against a database within a VPC because an elastic network interface (ENI) needs to be dynamically created between the lambda function and the VPC. The only way around this that I know of is to move your database instance outside the VPC. I don't know if this applies to your setup but may. 

Regarding web app performance, what types of caching have you implemented so far?

**Comment by paul-pries-weatherlogics** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html
This is the main bit that was I was referring to, where it says that any declarations made outside of the handler function can be maintained and reused, including connections.

https://www.jeremydaly.com/reuse-database-connections-aws-lambda/
This post goes into a bit of detail about how to implement this.

The guy who actually wrote the web app is pretty sure the database is in a VPC, so I'll look into how or if I can change that.

The only caching being used currently is Amazon API caching.

**Comment by ARolek** [comment]
@paul-pries-weatherlogics very interesting. Some additional articles that are applicable:

- [AWS Lambda Execution Context](https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html)
- [AWS Lambda Function Handler in Go: Using Global State](https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-handler-types.html#go-programming-model-handler-execution-environment-reuse)

This could be a great optimization and from my brief research is something the codebase is positioned to implement.

For immediate performance, I would suggest implementing tegola's [S3 tile cache](https://tegola.io/documentation/configuration/#s3) so the tiles don't need to be regenerated on every request.

**Comment by ARolek** [comment]
I'm going to re-open this one as it's something I would like to implement eventually.

**Comment by ARolek** [comment]
@paul-pries-weatherlogics I just pushed up some code to the branch `issue-609` that addresses this issue. If you have some time, it would be great to get your review/testing to see if the change is performing as desired.

**Comment by ARolek** [comment]
@paul-pries-weatherlogics this is now in the v0.11.x branch.

**Comment by musmanalibaloch** [comment]
Hi guys, this article can help you to reuse db connection in lambda environment. 
https://muhammadusmanalibaloch.medium.com/aws-lambda-reuse-database-connection-and-save-around-200ms-response-time-2c50a445f464

**Comment by ARolek** [comment]
@musmanalibaloch yep, this was implemented in the PR #670
