### ISSUE TITLE
Tegola behind nginx for https

### ISSUE THREAD

**Issue by pmabey** [go-spatial/tegola#637]
Does anyone have a working nginx config they could share for serving tegola over https? I tried with the following but it complains about not finding the capabilities file. It seems to be looking in the wrong root directory but I can't figure out how to fix that. 

        location /tegola/ {
           proxy_pass http://localhost:9090/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $http_x_forwarded_for;
           proxy_redirect off;
           proxy_buffering off;
        }

**Comment by ARolek** [comment]
@pmabey this issue has not made it's way to the docs on tegola.io yet, but it refers to the issue you're having: https://github.com/go-spatial/tegola-docs/issues/35. If you need to have `/tegola/` be a prefix you might need to use the webserver `hostname` config param: https://tegola.io/documentation/configuration/#webserver

**Comment by pmabey** [comment]
Thanks, this is useful. Can you suggest what hostname should be set to? I tried example.com, as well as example.com/tegola/.  The error message I am getting in nginx is below. If I point my browser at http://example.com/tegola/capabilities the file is found fine. But somewhere it seems to be wanting to goto my root directory instead. 

2019/08/22 22:08:11 [error] 12703#0: *1 open() "/var/www/html/capabilities" failed (2: No such file or directory), client: 1.1.1.1, server: example.com, request: "GET /capabilities HTTP/1.1", host: "example.com", referrer: "http://example.com/tegola/"

**Comment by ARolek** [comment]
I think you need to remove the trailing slash on `https://example.com/tegola/` so it reads `https://example.com/tegola`. If you try hitting `https://example.com/tegola/capabilities` you can see the URLs that tegola is forming in the JSON response. Make sure they match what you're expecting.

**Comment by ARolek** [comment]
@pmabey I just cut a new version of tegola which allows you to set the `uri_prefix` under the webserver config block. For example:

```toml
[webserver]
uri_prefix = tegola
```

This should address your issue. Let me know if you have any problems using it.

**Comment by pmabey** [comment]
I couldn't get it working without the trailing slash but the latest version with the uri_prefix works great. Thank you so much for adding that.

**Comment by ARolek** [comment]
@pmabey great news. I'm glad it's working for you and thanks for following up!
