### ISSUE TITLE
Docker instructions don't appear to be working

### ISSUE THREAD

**Issue by JoshGore** [go-spatial/tegola#644]
config file exists and works if I run ./tegola however the docker container does not appear to find.
```
root@wty-docker:~# docker run -v $HOME/WalkTheYorkeTegola:/opt/tegola_config -p 8080 gospatial/tegola serve
2019-09-08 10:03:45 [INFO] root.go:61: Loading config file: config.toml
2019-09-08 10:03:45 [INFO] config.go:207: loading local config (config.toml)
Error: config file at location (config.toml) not found!
Usage:
  tegola serve [flags]

Aliases:
  serve, server

Flags:
  -h, --help          help for serve
  -n, --no-cache      turn off the cache
  -p, --port string   port to bind tile server to (default ":8080")

Global Flags:
      --config string   path to config file (default "config.toml")

config file at location (config.toml) not found!
root@wty-docker:~# ls $HOME/WalkTheYorkeTegola/
config.toml  README.md  tegola
root@wty-docker:~# 
```

**Comment by gdey** [comment]
The config file name needs to be `config.toml` in the `/opt` directory. 

Can you try:
`docker run -v $HOME/WalkTheYorkeTegola:/opt/config.toml -p 8080 gospatial/tegola serve`

(Note I have not tried this.)

**Comment by gdey** [comment]
Instructions here are wrong: https://hub.docker.com/r/gospatial/tegola/
It should have a `--config /opt/tegola_config/config.toml` at the end of the command for the `Example PostGIS use w/ local config:` section.

**Comment by JoshGore** [comment]
Ah that makes sense, thanks!

**Comment by ARolek** [comment]
I updated the DockerHub instructions. Sorry about that.
