### ISSUE TITLE
Can not find dependecy files or folder after Rewriting Url to Tegolo server

### ISSUE THREAD

**Issue by th-turk** [go-spatial/tegola#652]
I have run tegolo server to my local machine and it works  correctly.
But when i decide to publish this tegolo default tilemap to someone i have to rewrite my url from  accessable url.

its loading all dependecy  files but when it downoad
capabilities/*.json file Sub path change to base path like 

http://HostName/vectortile/app/capabilities/ (Get File Successfully ) but  .json request from this path 
"http://HostName/capabilities/*.json"

When i chance path to "http://HostName/vectortile/app/capabilities/*.json" i am able to access folder should be download .

**Comment by gdey** [comment]
Have you tried to set the [`hostname`](https://tegola.io/documentation/configuration/#webserver) webserver config, to the accessible hostname?

**Comment by th-turk** [comment]
Yes I have tried this. But `hostname` convert it to urlencoding characters. So it didn't work.
I also set `cros origin` config just the problem is probably in `server`  build folder. I checked code and they combine root url path  with other generated file names. I tried to build it manually but the steps in documentations didn't work for me.
Build command couldn't find go files under github.com packages.

**Comment by ARolek** [comment]
@th-turk I think you're looking for the `uri_prefix` config. This is a new config param and it's not documented on tegola.io yet. You can see it documented in the [server/README.md](https://github.com/go-spatial/tegola/tree/master/server#config-properties)

**Comment by th-turk** [comment]
@ARolek  Thank you so much for your help. This new feauture workes well. If you are using proxy for  your server.
But i think without  `url_prefix` params it should'nt  get root path while ceneratin capabilities folder and  *.json file. 
Usin subpath would also work .

**Comment by ARolek** [comment]
@th-turk I'm not quite sure what you're asking. Did the `uri_prefix` solve your problem or are you still encountering an issue?

**Comment by th-turk** [comment]
@ARolek as I said this parameter fixed my issue. Thank you so much for your help :)

**Comment by ARolek** [comment]
@th-turk great to hear, and anytime!
