### ISSUE TITLE
Best way to deal with concurrent connections / requests?

### ISSUE THREAD

**Issue by andrestone** [go-spatial/tegola#671]
Hi!

I've been playing with tegola a bit and it seems like a "regular" Postgres instance isn't a good fit for the application, since I often get messages complaining about `max_connections`.

Is there any sort of guide on how one should deploy tegola + postgres in production? Should I increase memory and `max_connections` and run in a couple of instances only? Is it better to have multiple smaller instances in parallel behind a load balancer?

Just looking for general advice.

Thanks.

**Comment by ARolek** [comment]
@andrestone hey there! It sounds like what you're hitting is a configuration issue with between tegola and your local Postgres instance. Tegola uses a connection pool to maintain connections with Postgres. The default max connections is set to 100. If this is higher than what your Postgres connection allows then you will start seeing errors in the console once the pool can no longer expand to meet request demand. You can adjust this via the data provider config `max_connections` (which it sounds like you already found). Associated documentation: https://tegola.io/documentation/configuration/#postgis

Regarding production deployment that's very dependent on your situation (i.e. data update intervals, concurrent user expectations, available caching mechanisms). It might be easier to talk through your goals via chat. If you're interested you can join us on Slack: http://slack.go-spatial.org/

**Comment by andrestone** [comment]
Thanks, @ARolek!
