### ISSUE TITLE
SSL (https) on tegola

### ISSUE THREAD

**Issue by ocasti** [go-spatial/tegola#672]
Tegola not work under ssl domain, the server rejected tiles if domin is https

**Comment by ARolek** [comment]
@ocasti this is a dupe of #82. This has also been addressed in the v0.11.x branch but it's not yet in master. You can take a look at the PR here: https://github.com/go-spatial/tegola/pull/455

**Comment by ARolek** [comment]
@ocasti this feature is now available in the most recent release of tegola. Please give it a run when you have a chance: https://github.com/go-spatial/tegola/releases

**Comment by ARolek** [comment]
Oh and the associated docs (not yet on tegola.io): https://github.com/go-spatial/tegola/tree/master/server#config-properties
