### ISSUE TITLE
Geometry processing regression in v0.11.0 release

### ISSUE THREAD

**Issue by zaa76** [go-spatial/tegola#682]
![image](https://user-images.githubusercontent.com/10848270/81308147-20e53400-908a-11ea-9cf2-32321fd6bc6b.png)
![image](https://user-images.githubusercontent.com/10848270/81308301-496d2e00-908a-11ea-8838-25e2a3833279.png)

**Comment by ARolek** [comment]
@zaa76 hmm, that's interesting. The geometry processing updates were pulled out of the v0.11.x release. I will need to review the commit log again, but you should not be seeing this regress. cc: @gdey @ear7h

**Comment by ARolek** [comment]
I have confirmed that the v0.11.0 release has included commits that were not supposed to be carved out for v0.12.x and are causing geom rendering issues. I'm working on a patch release.

**Comment by ARolek** [comment]
@zaa76 I just cut v0.11.1 which should fix this regression.

**Comment by zaa76** [comment]
Hello!
It looks like the problem is fixed
thank
![image](https://user-images.githubusercontent.com/10848270/81395039-9ce38880-912b-11ea-9e11-9e310ae986d4.png)

**Comment by ARolek** [comment]
Great!
