### ISSUE TITLE
map.go:261 v0.11.1

### ISSUE THREAD

**Issue by zaa76** [go-spatial/tegola#683]
2020/05/08 12:26:16 map.go:261: err fetching tile (z: 10, x: 577, y: 354) features: err making geometry valid: context canceled
2020/05/08 12:26:18 map.go:261: err fetching tile (z: 11, x: 1156, y: 711) features: err making geometry valid: context canceled
2020/05/08 12:26:21 map.go:261: err fetching tile (z: 11, x: 1153, y: 710) features: err making geometry valid: context canceled
2020/05/08 12:26:21 map.go:261: err fetching tile (z: 11, x: 1153, y: 711) features: err making geometry valid: context canceled
2020/05/08 12:26:21 map.go:261: err fetching tile (z: 11, x: 1153, y: 710) features: err making geometry valid: context canceled
2020/05/08 12:26:22 map.go:261: err fetching tile (z: 11, x: 1154, y: 711) features: err making geometry valid: context canceled
2020/05/08 12:26:22 map.go:261: err fetching tile (z: 11, x: 1155, y: 711) features: err making geometry valid: context canceled
2020/05/08 12:26:32 map.go:261: err fetching tile (z: 12, x: 2309, y: 1420) features: err making geometry valid: context canceled
2020/05/08 12:26:36 map.go:261: err fetching tile (z: 12, x: 2308, y: 1422) features: err making geometry valid: context canceled
2020/05/08 12:26:43 map.go:261: err fetching tile (z: 11, x: 1155, y: 710) features: err making geometry valid: context canceled
2020/05/08 12:27:08 map.go:261: err fetching tile (z: 12, x: 2310, y: 1421) features: err making geometry valid: context canceled
2020/05/08 12:28:12 map.go:261: err fetching tile (z: 13, x: 4620, y: 2841) features: err making geometry valid: context canceled
2020/05/08 12:28:12 map.go:261: err fetching tile (z: 13, x: 4619, y: 2841) features: err making geometry valid: context canceled
2020/05/08 12:28:14 map.go:261: err fetching tile (z: 12, x: 2309, y: 1420) features: err making geometry valid: context canceled
2020/05/08 12:28:21 map.go:261: err fetching tile (z: 12, x: 2310, y: 1420) features: err making geometry valid: context canceled
2020/05/08 12:28:21 map.go:261: err fetching tile (z: 11, x: 1155, y: 710) features: err making geometry valid: context canceled
2020/05/08 12:28:37 map.go:261: err fetching tile (z: 12, x: 2310, y: 1421) features: err making geometry valid: context canceled
2020/05/08 12:28:39 map.go:261: err fetching tile (z: 14, x: 9238, y: 5684) features: err making geometry valid: context canceled
2020/05/08 12:28:56 map.go:261: err fetching tile (z: 2, x: 1, y: 1) features: err making geometry valid: context canceled
2020/05/08 12:28:57 map.go:261: err fetching tile (z: 3, x: 4, y: 3) features: err making geometry valid: context canceled
2020/05/08 12:29:00 map.go:261: err fetching tile (z: 2, x: 2, y: 1) features: err making geometry valid: context canceled
2020/05/08 12:29:00 map.go:261: err fetching tile (z: 3, x: 4, y: 2) features: err making geometry valid: context canceled
2020/05/08 12:29:02 map.go:261: err fetching tile (z: 6, x: 38, y: 22) features: err making geometry valid: context canceled
2020/05/08 12:29:02 map.go:261: err fetching tile (z: 6, x: 37, y: 22) features: err making geometry valid: context canceled
2020/05/08 12:29:22 map.go:261: err fetching tile (z: 4, x: 9, y: 4) features: err making geometry valid: context canceled
2020/05/08 12:29:23 map.go:261: err fetching tile (z: 4, x: 8, y: 4) features: err making geometry valid: context canceled
2020/05/08 12:29:30 map.go:261: err fetching tile (z: 3, x: 4, y: 2) features: err making geometry valid: context canceled
2020/05/08 12:29:30 map.go:261: err fetching tile (z: 3, x: 3, y: 2) features: err making geometry valid: context canceled

**Comment by zaa76** [comment]
part of my config:
...
   [[providers.layers]]
        name = "ocean-z0-z2"
        geometry_fieldname = "geom"
        geometry_type = "MultiPolygon"
        sql = """
            SELECT ST_AsBinary(geometry) AS geom
                FROM osm_ocean_polygon_gen6 WHERE geometry && !BBOX!
        """

   [[providers.layers]]
        name = "ocean-z3-z6"
        geometry_fieldname = "geom"
        geometry_type = "MultiPolygon"
        sql = """
            SELECT ST_AsBinary(geometry) AS geom
                FROM osm_ocean_polygon_gen5 WHERE geometry && !BBOX!
        """
...
...
    [[maps.layers]]
        provider_layer = "world_data.ocean-z0-z2"
#        dont_simplify = true
#        dont_clip = true
        min_zoom = 0
        max_zoom = 2

    [[maps.layers]]
        provider_layer = "world_data.ocean-z3-z6"
#        dont_simplify = true
#        dont_clip = true
        min_zoom = 3
        max_zoom = 6
...
 Generalize tables SQL:
shp2pgsql -s 3857 -I -g geometry water-polygons-split-3857/water_polygons.shp osm_ocean_polygon | psql

CREATE TABLE osm_ocean_polygon_gen6 AS SELECT ST_Simplify(geometry, 640) AS geometry FROM osm_ocean_polygon

**Comment by ARolek** [comment]
@zaa76 this is fixed in the v0.11.2 release. Thanks for the report(s).
