### ISSUE TITLE
Too much third party dependence.

### ISSUE THREAD

**Issue by yygis** [go-spatial/tegola#686]
Too much third party dependence.
Security and upgrades may be a lot of things to deal with,and it also makes the package larger.

**Comment by ARolek** [comment]
@devCopper thanks for opening the conversation, but I feel "too much" is an arbitrary statement and tough benchmark to work towards. A few things to note:

> Security and upgrades may be a lot of things to deal with

I generally agree, and we work on keeping the dependency graph of tegola reasonably ligh. A great deal of the dependency graph is from the various data and cache providers (i.e. postgis, geopackage, redis, s3, azure blob store, etc). If you're looking to perform a security audit, and want to stay focused, consider building tegola from source and use build tags to reduce the data providers and cache providers to only what you need: https://github.com/go-spatial/tegola#building-from-source. 

>  it also makes the package larger

This is true, but not all code in the vendor directory is going to be compiled in, only what the program uses. If the binary size is of concern you can use the build tags I referenced above to reduce the binary size to only include what you need.

**Comment by mapl** [comment]
I think Tegola's binary size is fairly small compared to "other" golang projects.

If you compile from source you can leverage some build ldflags to reduce its size.

A comprehensive overview how to do this this is provied by https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Have fun!

**Comment by gdey** [comment]
@devCopper did @ARolek and @mapl answer your concerns? If so, could be we close this issue?
