### ISSUE TITLE
Two "name" parameters in documentation

### ISSUE THREAD

**Issue by yaras-phoenix** [go-spatial/tegola#697]
Reading the doc I felt a bit confused with the  following: 
![image](https://user-images.githubusercontent.com/37367584/85838626-2281cd00-b79a-11ea-9156-4801c931c21c.png)

The 2nd "name" parameter seems to be related to map layers, not maps. Do I get it right?

**Comment by gdey** [comment]
Thank you for finding this issue.

Yes, you are correct. That is a bug in the documentation. It should not be there. It's the name parameter in the Map Layers that it is referring to.

**Comment by gdey** [comment]
Moving issue to the docs repo.
https://github.com/go-spatial/tegola-docs/issues/48
