### ISSUE TITLE
docker build error: unsatisfiable constraints: gcc-9.3.0-r0

### ISSUE THREAD

**Issue by embeepea** [go-spatial/tegola#712]
Hi,

I've been working with tegola in docker for a couple of months, regularly rebuilding my docker image using the Dockerfile in the tegola repo, and I recently started getting the following build error when the builder runs "apk add gcc=9.2.0-r4":

> ERROR: unsatisfiable constraints:
>   gcc-9.3.0-r0:
>     breaks: world[gcc=9.2.0-r4]

I'm not aware of having changed anything that would cause this.  I'm wondering if it's possible that the golang:1.14.1-alpine3.11 container image used as a base has been updated to include gcc-9.3.0-r0 and is now incompatible with gcc-9.2?  I'm still relatively new to docker and would think that the tag golang:1.14.1-alpine3.11 would refer to a specific image that doesn't change, but maybe it does get periodic updates?

In any case, I wonder if others have also recently starting getting this error?

**Comment by ARolek** [comment]
@embeepea I believe @gdey has a fix for this here: https://github.com/go-spatial/tegola/pull/700/commits/f72b52e91846386e3131661483d7f210d0872af4

This is about to hit the v0.12.x branch and we're just about ready for release. What branch are you working against?

**Comment by embeepea** [comment]
I've mostly been using 0.11.2, but I tried with 0.12.x this morning and got the same error.

Changing the Dockerfile to "apk add gcc=9.3.0-r0" as in @gday's fix does seem to resolve the issue, at least in the sense that the build succeeds with no error.  (I haven't yet had a chance to actually confirm that the resulting image works correctly.)

**Comment by ARolek** [comment]
@embeepea please let me know if you have any issues with the Dockerfile change as we're going to be cutting a new version of tegola here real soon with that change.

**Comment by embeepea** [comment]
I just tested with  @gdey's fix f72b52e; it seems to work fine for me.  Thanks!

**Comment by ARolek** [comment]
@embeepea great! I'm going to close this issue for now as we're about to merge v0.12.x and we're going to cut that version this week. If you have a chance it would be great if you could test v0.12.x branch in your deployment.

**Comment by embeepea** [comment]
Just to clarify: the fix isn't currently in the v0.12.x branch because the PR (actually there are 2 PRs) containing haven't been accepted/merged yet, right?  When I tested, I did so using the head of the normalize_table_tests branch, which is the branch in https://github.com/go-spatial/tegola/pull/711.

I'll try to keep an eye on v0.12.x and will test again once I notice the fix is there.

**Comment by ARolek** [comment]
Correct. @gdey should be merging those PRs into v0.12.x today / tomorrow.

**Comment by gdey** [comment]
@embeepea I have merged those two PR into v0.12.x. We should be releasing that version sometime this week.
