### ISSUE TITLE
Can´t run tegola_lambda

### ISSUE THREAD

**Issue by ocasti** [go-spatial/tegola#713]
I try to run tegola under lambda server but return this error on test:

{
  "errorMessage": "neither APIGatewayProxyRequest nor ALBTargetGroupRequest received",
  "errorType": "errorString"
}

![imagen](https://user-images.githubusercontent.com/2475408/90304901-1a810800-de82-11ea-9185-80e05f21648a.png)

On browser:

api-gateway/capabilities
{"message":"Not Found"}

api-gateway/

![imagen](https://user-images.githubusercontent.com/2475408/90304919-68960b80-de82-11ea-983c-932f0e348f81.png)

**Comment by ARolek** [comment]
@ocasti can you provide some more details about the setup? 

* Are you running behind API gatway or an ALB? (Looks like api gateway)
* Have you configured tegola with a `uri_prefix`?
* Have you been able to issue a test payload request to the `/capabilities` endpoint from lambda? 

If you don't need API Gateway, I find the Application Load Balancer setup easier. The one critical detail is making sure that multi-part headers are enabled for the ALB, which is not part of the initial setup flow in the AWS console.

**Comment by ARolek** [comment]
@ocasti I'm going to close this issue for now, but feel free to re-open if you have additional questions.
