### ISSUE TITLE
Trying to add external SQL file (Попытка добавить внешний SQL file ) tegola v0.12.x

### ISSUE THREAD

**Issue by zaa76** [go-spatial/tegola#716]
[[providers]]
     database = "osm"
     host = "x.x.x.x"
    max_connections = 100
     name = "osm"
     password = "xxxxxxxxx"
     port = "5432"
     srid = 3857
     type = "mvt_postgis"
     user = "gis"
    
     [[providers.layers]]
     geometry_fieldname = "geom"
     geometry_type = "Polygon"
     name = "landcover-low-zoom"
     id_fieldname = "id"
     sql = """%./tegola_osm_carto_mvt_sql/landcover-low-zoom.sql%"""

could not register providers: could not generate sql, for layer(landcover-low-zoom): ERROR: syntax error at or near "%" (SQLSTATE 42601)

log db:

STATEMENT:  SELECT * FROM %./tegola_osm_carto_mvt_sql/landcover-low-zoom.sql% LIMIT 0;

**Comment by ARolek** [comment]
@zaa76 we don't currently support loading an external file. The SQL must be inline in the config. Another approach you can take is to create a stored procedure in your database and then call it from the config file.

**Comment by zaa76** [comment]
I saw this approach in this:
https://raw.githubusercontent.com/openmaplt/vector-map/master/config.toml.template

**Comment by dBitech** [comment]
that file is processed by
https://github.com/openmaplt/vector-map/blob/master/generate_config.sh to
create the resulting sql-inline config file.
