### ISSUE TITLE
Is vector tile with different projection supported yet?

### ISSUE THREAD

**Issue by exotfboy** [go-spatial/tegola#720]
There has been a lot of discussion about generating vector tiles in different projection besides 3857.

https://github.com/go-spatial/tegola/issues/243 https://github.com/go-spatial/tegola/issues/267 https://github.com/go-spatial/tegola/issues/668

And in the readme I found:

>Support for Web Mercator (3857) and WGS84 (4326) projections.

I wonder what does this mean? Are the projections mentioned above bound with source data or vector tile?

**Comment by jj0hns0n** [comment]
Currently only source data. There is an open PR to address 4326 tiles, but it hasnt been worked on in a while. https://github.com/go-spatial/tegola/pull/681
