### ISSUE TITLE
Cannot set maxZ

### ISSUE THREAD

**Issue by khumps** [go-spatial/tegola#725]
After looking through code and issues after getting an error `2020-11-10 20:12:58 [WARN] handle_map_layer_zxy.go:54: invalid Z value (23)` and found out that it is hardcoded to 22 as per https://github.com/go-spatial/tegola/issues/354#issuecomment-371609680

We are trying to support a map that goes down to 27. Long term, this should respect the configuration value specified in the config (we set max_zoom = 27 in our toml) but at least short term can the const be increased?

**Comment by ARolek** [comment]
@khumps can you help me understand a bit more about your requirement? A max zoom of 27 will create a massive amount of tiles (i.e. trillions). With vector tiles, you should not need to really go beyond zoom 16. The client-side can then over zoom the vector tiles and use client-side styling to show and hide features at higher zooms. 

So in theory, the max zoom in your tegola config should actually be 16 and you should include all your high fidelity data at that zoom. From there the client can handle the rest of the feature display logic.

**Comment by khumps** [comment]
@ARolek thanks for that insight, we will try handling it with client side zoom. Thanks!
