### ISSUE TITLE
Tegola Web Viewer Is Black/Not showing anything

### ISSUE THREAD

**Issue by istancescu** [go-spatial/tegola#733]
Hi,

I am currently trying to access bonn default tutorial data using the viewer on a local instance on both windows64/darwin64 but when I go to localhost:8080 the internal viewer is black. 
I can see the capabilities in left(river, etc) but the map is blank

Any idea what I did wrong or is there any issue with the internal viewer currently?

Thanks

**Comment by ARolek** [comment]
can you try adding the query string `?debug=true` to the URL (before the `#`)? I want to see if any debug lines start showing up for you at the tile seems.

**Comment by istancescu** [comment]
```


main_roads(� x
lakes(� xQ
debug-tile-outline"	�@�@�?type"
debug_buffer_outline(� xU
debug-tile-center"	�� typezxy"

debug_text"

Z:5, X:2, Y:5(� x
```

that's what I get while i do debug, the problem is not anyway the query part cause that is working, cause I can see with mapbox the vectors, but I cannot see anything on internal visualiser

![image](https://user-images.githubusercontent.com/22798055/103957057-8b3b0080-5152-11eb-9e4e-cd28851c1ce1.png)

**Comment by ARolek** [comment]
What browser are you using? Do you see any hints in the developer console?

**Comment by istancescu** [comment]
I am using Chrome, doesn't work on Safari either(just tried). 

The developer console is clear.

**Comment by ARolek** [comment]
@istancescu are you seeing any map controls in the lower right hand corner? For example:

<img width="235" alt="Screen Shot 2021-01-08 at 3 39 32 PM" src="https://user-images.githubusercontent.com/667850/104072123-62048980-51bf-11eb-9f5e-58722d141e1d.png">

If you're not seeing those, I would assume something is blocking mapbox gl from initializing. Maybe WebGL is blocked?

**Comment by istancescu** [comment]
Yes, I can see the controla in the lower right hand corner, but the map is all blocked.

Mentioning I have the same issue on a Macbook but also on a Windows device, using the get started bonn tutorial.

**Comment by ARolek** [comment]
@istancescu I wonder if you're just not zoomed in to the right location. The quickstart should navigate you right to Bonn, so if this is not happening it's a bug, but I want to make sure we're not dealing with some other rendering bug. 

What's the URL in your browser?

**Comment by istancescu** [comment]
The URL is http://localhost:8080/#0.44/0/0

**Comment by mapl** [comment]
Please try

http://localhost:8080/#11/50.7374/7.0982

which is at the location coords for Bonn, Germany 

Zoom Level: 11
Latitude: 50.7374
Longitude: 7.0982

**Comment by istancescu** [comment]
Oh, it is working like this.

But its there any reason why its not redirecting me to bonn already, or any way to make the bonn map viewable without a zoom level?

**Comment by ARolek** [comment]
@istancescu it actually should be. I need to update the example config. Try making this adjustment:

```toml
[[maps]]
name = "bonn"
center = [50.7374, 7.0982, 11.0] # include the center of the map so the user can be auto navigated to context
```

Once that's in place, the viewer should automatically navigate you to the map center.

**Comment by istancescu** [comment]
Thank you.
