### ISSUE TITLE
House number

### ISSUE THREAD

**Issue by adriantabirta** [go-spatial/tegola#739]
- How to setup config.toml to show on map street name and house number?
- How to apply Mapbox style or any other styles?

**Comment by ARolek** [comment]
@adriantabirta Take a look at the [tegola-osm](https://github.com/go-spatial/tegola-osm) repo for some configuration hints. For example you can see some of the config around the transport lines here: https://github.com/go-spatial/tegola-osm/blob/master/tegola.toml#L557.  

You can find some styles that work off the tegola-osm schema in the [tegola-web-demo](https://github.com/go-spatial/tegola-web-demo/tree/master/styles) repo. Check out the various styles and look for "transport_lines". You can then see how the styles are referencing the encoded geometries from the tegola config. 

Hopefully this gets you headed in the right direction.

**Comment by ARolek** [comment]
Also note that you can load the stiles from the `tegola-web-demo` repo into Fresco, our vector style editor and start playing with some cartography. Check it out: https://fresco.gospatial.org

**Comment by ARolek** [comment]
@adriantabirta I'm closing this issue for now, but if you need additional help feel free to re-open it.
