### ISSUE TITLE
Pre-rendering 

### ISSUE THREAD

**Issue by MacaScull** [go-spatial/tegola#740]
Hello, I was just wondering if there was anyway to pre-render vector tiles using tegola, as at the moment my map uses this but takes quite sometime to load in the map this way. 

Ive heard doing things like setting a min and max zoom on levels can do this, but when ive done this data dissappears off the map when I exceed that zoom level, any advice to get faster rendering times on vector data?

**Comment by dBitech** [comment]
ye, you can seed the tile cache (Create the tiles and store them in the
tegola caching system:
https://tegola.io/documentation/cache-seeding-and-purging/#seed1

**Comment by MacaScull** [comment]
Is there a way to access this as an environment variable in a docker-compose? or will this have to be one in a different way? if it can be accessed in a docker-compose file, could you provide an example?

**Comment by ARolek** [comment]
@MacaScull it's calling tegola as a command, for example:

```console
$ tegola cache seed --config your_config.toml
````

It's not running tegola as a service, but rather a worker. This should work with Docker Compose.

**Comment by ARolek** [comment]
Closing this issue as I believe the question has been answered. Re-open if you need additional clarifcaiton.
