### ISSUE TITLE
Point clustering

### ISSUE THREAD

**Issue by zakjan** [go-spatial/tegola#753]
Is it possible to implement server-side point clustering with Tegola, for use cases with high point count and low zoom level?

Currently it's possible with custom implemented Node.js service using [supercluster](https://github.com/mapbox/supercluster) and [vt-pbf](https://github.com/mapbox/vt-pbf), connected to PostGIS data source. I'm looking for an out-of-the-box solution.

**Comment by ARolek** [comment]
@zakjan I have not had to do clustering server-side yet, but it looks like the functions you need are availalbe in PostGIS. Have you played with [ST_ClusterDBSCAN](https://postgis.net/docs/ST_ClusterDBSCAN.html) yet? 

If you do dive into using this function, I would be interested in seeing the solution you come up with as I think it could help others. I'm happy to help with the research if need be.

**Comment by edtjones** [comment]
@zakjan did you ever get anywhere with serverside clustering? I would love to hear your progress if you did.

**Comment by iwpnd** [comment]
Definitely possible.

Say you have a bunch of points in your provider. You create two layers.
1. layer uses the center point of a cluster as geometry field
2. layer uses the default geometry field of your points

Then building your map, you use the first layer with the center points of the clusters from zoom level x to y and the second layer from y to z.

For static geometry data I suggest to create the cluster center points and store them in the database. For infrequently changing point data I suggest caching and for frequently changing data I suggest either a big database instance or another approach.

**Comment by edtjones** [comment]
@iwpnd thats a really clever idea! I’ve got relatively static data AND a big database server, so I think I can cache these clusters in the db and judiciously update with triggers. Thanks for the insight! 🙂

**Comment by iwpnd** [comment]
I created an example over at [iwpnd/tegola-cluster-points](https://github.com/iwpnd/tegola-cluster-points). I didn't really bother with performance here but from I can see, this seems viable.

**Comment by edtjones** [comment]
Wow - great! Thanks Ben.

**Comment by ARolek** [comment]
I'm going to close this issue for now. Thanks for helping @iwpnd
