### ISSUE TITLE
Add Prometheus support for Cache Providers

### ISSUE THREAD

**Issue by gdey** [go-spatial/tegola#756]
The Cache metrics will be prefixed with `tegola_cache_` and the following things will be observed

Each one will have a label of `type` that will be the cache type name

* misses_total is a counter of the total number of misses
* hits_total is a counter of the total number of hits
* flight_request is a gauge of the cache requests currently being served
* duration_seconds is a histogram of the duration of the current get cache requests, partitioned by map_name/map_layer, and z. 
* response_size_bytes is a histogram of response sized in bytes with the following buckets, 500kb, 1 KB, 10 KB, and 1 MB.
* errors is the number of errors from a get operation (that is not a miss error)
* set_duration_seconds is a histogram of the duration for filling the cache after a miss.
* set_errors is the number of errors from a get operation

**Comment by gdey** [comment]
@johngian which cache providers you think I should make sure to implement first. And if the above makes sense.

**Comment by ARolek** [comment]
@gdey I wonder if we should adjust the `response_size_bytes` a bit to include a 500kb bucket as 500kb is a warning threshold for tile size. We could potentially drop the 5+mb and bucket anything over 1MB

**Comment by johngian** [comment]
@gdey I think a good start is to add support for the fs based backend and s3.

**Comment by johngian** [comment]
@gdey Can you ellaborate a bit on the `duration_seconds` metric? Is it the time for the cache get operation?

Some suggestions for the cache metrics:
* Cache get time histogram
* Cache set time histogram
* Errors counter
* Different labels for cache operations on
  * `tegola serve`
  * `tegola cache seed` 
  * `tegola cache purge`

**Comment by gdey** [comment]
@johngian for the `tegola cache` sub command I would assume we would need to setup Prometheus push type configuration?

**Comment by ARolek** [comment]
@gdey that's a good point as the cache seed / purge commands don't have a server component, there's no `/metric` endpoint available. For seeding / purging maybe it makes more sense to analyze the log output?

**Comment by johngian** [comment]
Can't we have a configuration for that and maybe allow exposing the `/metrics` endpoint for the cache subcommand.

**Comment by ARolek** [comment]
@gdey we could add a `push_url` to the observer config to allow for ephemeral job reporting.

**Comment by gdey** [comment]
> Different labels for cache operations on
> 
>     * `tegola serve`
> 
>     * `tegola cache seed`
> 
>     * `tegola cache purge`

wouldn't you set these labels in the Prometheus configs?

**Comment by johngian** [comment]
As long as its configurable then that's fine. My point is mostly about being able to differentiate the metrics between different use cases.

**Comment by ARolek** [comment]
@gdey 

>wouldn't you set these labels in the Prometheus configs?

Do you know how this would work for push? I have not checked into how Prometheus configs work for ephemeral jobs.
