### ISSUE TITLE
string format cache seed

### ISSUE THREAD

**Issue by r4naf** [go-spatial/tegola#769]
Tell me how to write the command correctly?

`sudo /home/user1/tegola_server/tegola --config=/home/user1/tegola_server/config_my.toml cache seed --map "geo3" bounds "49.93428, 58.50279, 49.42342, 58.69525" max-zoom=13 min-zoom=12`

> 2021-04-05 11:42:02 [INFO] root.go:61: Loading config file: /home/user1/tegola_server/config_my.toml
> 2021-04-05 11:42:02 [INFO] config.go:305: loading local config (/home/user1/tegola_server/config_my.toml)
> 2021-04-05 11:42:02 [INFO] providers.go:82: registering provider(type): geo3 (postgis)
> 2021-04-05 11:42:02 [INFO] seed_purge.go:187: zoom list: [0]
> 2021-04-05 11:42:02 [INFO] cache.go:204: waiting for workers to finish up
> 2021-04-05 11:42:02 [INFO] worker.go:72: cache seed set to not overwrite existing tiles. skipping map (geo3) tile (0/0/0)
> 2021-04-05 11:42:02 [INFO] cache.go:214: all workers are done
> 2021-04-05 11:42:02 [INFO] provider.go:256: cleaning up providers
> 2021/04/05 11:42:02 postgis.go:682: cleaning up postgis providers

Nothing works ... no tiles are created. Coordinates changed places in different ways. No result.

**Comment by ARolek** [comment]
@r4naf try this refactored command

```console
/home/user1/tegola_server/tegola cache seed --config=/home/user1/tegola_server/config_my.toml --map "geo3" -- bounds "49.93428, 58.50279, 49.42342, 58.69525" --min-zoom=12 --max-zoom=13 
```

A few notes:

* you're using the `--config` flag prior to the command `cache seed`
* Your `bounds`, `max-zoom` and `min-zoom` are all missing the double dash (`--`) in front of them so they're being ignored.

LMK if that helps.

**Comment by gdey** [comment]
@r4naf I'm assuming the thumbs up means that adding the missing `--` worked for you. 
Reopen if that is not the case.
