### ISSUE TITLE
Aws lambda Execution failed - /lib64/libc.so.6: version `GLIBC_2.28' not found 

### ISSUE THREAD

**Issue by matrottier** [go-spatial/tegola#789]
Trying to run Tegola with AWS lambda.  
i got this error when testing : 
`
START RequestId: 1340f6e4-ceee-401b-950b-cac0880a4f95 Version: $LATEST
/var/task/tegola_lambda: /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by /var/task/tegola_lambda)
END RequestId: 1340f6e4-ceee-401b-950b-cac0880a4f95
REPORT RequestId: 1340f6e4-ceee-401b-950b-cac0880a4f95	Duration: 35.30 ms	Billed Duration: 36 ms	Memory Size: 512 MB	Max Memory Used: 6 MB	
RequestId: 1340f6e4-ceee-401b-950b-cac0880a4f95 Process exited before completing request
`

i tried the version from github and a compiled version with go 1.3 and go 1.6.  
also tried the option "CGO_ENABLED=0" on the compilation without success

**Comment by ARolek** [comment]
@matrottier hmmm. We're currently using tegola_lambda to run the demo.tegola.io. I'm going to ask the obvious question first, can you confirm you're using the Go runtime in Lambda?

**Comment by matrottier** [comment]
i think so... there it is my console : 
![aws_lambda_tegola](https://user-images.githubusercontent.com/5638601/125515427-ec8d919d-8dff-4a0a-8f18-2d6fb1a2aabf.png)

**Comment by ARolek** [comment]
@matrottier that looks correct to me. When you built locally, did you use GOOS=linux? Does this same error happen when you use the [release builds](https://github.com/go-spatial/tegola/releases)?

**Comment by matrottier** [comment]
it happen with release builds AND locally builds. =/

**Comment by matrottier** [comment]
in an act of utter desperation,  
i tested a "layer" with the file "libc.so.6" in the folder "lib/lib64".  
2 environments variables: 
LD_DEBUG | all
LD_LIBRARY_PATH | /opt/lib/lib64/

there is the log : 
```
ibrary=libdl.so.2 [0]; searching
         7:	 search path=/opt/lib/lib64		(LD_LIBRARY_PATH)
         7:	  trying file=/opt/lib/lib64/libdl.so.2
         7:	 search cache=/etc/ld.so.cache
         7:	  trying file=/lib64/libdl.so.2
         7:	
         7:	file=libdl.so.2 [0];  generating link map
         7:	  dynamic: 0x00007f7bd2648d88  base: 0x00007f7bd2446000   size: 0x0000000000203130
         7:	    entry: 0x00007f7bd2446e60  phdr: 0x00007f7bd2446040  phnum:                  7
         7:	
         7:	
         7:	file=libc.so.6 [0];  needed by /var/task/tegola_lambda [0]
         7:	find library=libc.so.6 [0]; searching
         7:	 search path=/opt/lib/lib64		(LD_LIBRARY_PATH)
         7:	  trying file=/opt/lib/lib64/libc.so.6
         7:	 search cache=/etc/ld.so.cache
         7:	  trying file=/lib64/libc.so.6
         7:	
         7:	file=libc.so.6 [0];  generating link map
         7:	  dynamic: 0x00007f7bd243eb60  base: 0x00007f7bd2078000   size: 0x00000000003cd1e0
         7:	    entry: 0x00007f7bd209a680  phdr: 0x00007f7bd2078040  phnum:                 10
         7:	
         7:	checking for version `GLIBC_2.2.5' in file /lib64/libdl.so.2 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.3.2' in file /lib64/libpthread.so.0 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.2.5' in file /lib64/libpthread.so.0 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.28' in file /lib64/libc.so.6 [0] required by file /var/task/tegola_lambda [0]
         7:	/lib64/libc.so.6: error: version lookup error: version `GLIBC_2.28' not found (required by /var/task/tegola_lambda) (continued)
/var/task/tegola_lambda: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/tegola_lambda)
         7:	checking for version `GLIBC_2.14' in file /lib64/libc.so.6 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.3.4' in file /lib64/libc.so.6 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.4' in file /lib64/libc.so.6 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /var/task/tegola_lambda [0]
         7:	checking for version `GLIBC_2.2.5' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_PRIVATE' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_2.14' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_2.3.2' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_PRIVATE' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
         7:	checking for version `GLIBC_PRIVATE' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libdl.so.2 [0]
         7:	checking for version `GLIBC_PRIVATE' in file /lib64/libc.so.6 [0] required by file /lib64/libdl.so.2 [0]
         7:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libdl.so.2 [0]
         7:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libc.so.6 [0]
         7:	checking for version `GLIBC_PRIVATE' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libc.so.6 [0]
END RequestId: bc1edf0c-6e74-4b28-9659-a6fc502b3b2a
REPORT RequestId: bc1edf0c-6e74-4b28-9659-a6fc502b3b2a	Duration: 99.15 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 6 MB	
RequestId: bc1edf0c-6e74-4b28-9659-a6fc502b3b2a Process exited before completing request
```

**Comment by ARolek** [comment]
@matrottier I"m going to reopen this issue until I have a chance to investigate why the build pipeline is not producing a binary that just works. Here's the build command:

https://github.com/go-spatial/tegola/blob/126d51113f8ecf362a9235449161a0f62367895c/.github/workflows/on_release_publish.yml#L52-L58

It looks like you disabled CGO, but that's not desirable as Geopkg will not work without it. I'm not quite sure what changed (something with Lambda?) but I would like to make sure no one else has to deal with this juggle.

**Comment by ARolek** [comment]
@matrottier I was able to recreate your problem, and I'm not quite sure when this started. AWS Lambda runs on AmazonLinux and we're currently compiling on the GH Action runner `ubuntu-latest`. There's clearly a mismatch of GLIB location / version / expectations. I'm working on updating the CI so we don't encounter this anymore. 

Thanks again for reporting this.

**Comment by ARolek** [comment]
@matrottier can you try the binary output from this Github Action run: https://github.com/go-spatial/tegola/actions/runs/1043951686

I refactored the way we're building tegola_lambda and I'm now using Amazon Linux for that build. I'm hoping you can give it a test and confirm it's working on your end. It's working for me with my tests.

**Comment by matrottier** [comment]
it works !! (no problem with GLIBC) 
but i got this error from API gateway, any idea ?  
"Internal Server Error The IAM role configured on the integration or API Gateway doesn't have permissions to call the integration. Check the permissions and try again"

**Comment by ARolek** [comment]
@matrottier excellent! Thanks for checking that out. Regarding the IAM issue, that sounds like it has to do with your resource access control rules setup in your AWS account, not specific to tegola. I have personally found that using the Application Load Balancer easier to set up the API Gateway. Considering giving that a shot and then moving to API Gateway.

**Comment by ARolek** [comment]
@matrottier I just sent in a PR to fix this if you want to give it a look: https://github.com/go-spatial/tegola/pull/790

**Comment by matrottier** [comment]
trying to upgrade from 0.16 and i got the same message : 
```
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/bootstrap)
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /var/task/bootstrap)
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /var/task/bootstrap)
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /var/task/bootstrap)
```
with my own compiled binary, the file of the github 0.17, 0.18 and 0.19. 
i tested with SAM and in my CDK code i use this option : `runtime: lambda.Runtime.GO_1_X`. also tried `lambda.Runtime.PROVIDED_AL2,`  

searching for a hint ! :pray:

**Comment by matrottier** [comment]
move along, nothing to see here ! 
just a old man who has trouble with technology

it's working with `al2` and [tegola_lambda_amd64.zip](https://github.com/go-spatial/tegola/releases/download/v0.19.0/tegola_lambda_amd64.zip)
thanks for the quick reply @ARolek

**Comment by ARolek** [comment]
@matrottier nice! and anytime ;-)
