### ISSUE TITLE
crash seeding tile

### ISSUE THREAD

**Issue by probabilty** [go-spatial/tegola#796]
- query:
```
[[providers.layers]]
geometry_fieldname = "geom"
id_fieldname = "id"
name = "landuse_point"
sql = "SELECT a.osm_id as id, a.osm_type as type, a.name, b.tags, ST_AsBinary(a.geom) as geom FROM osm.landuse_point as a JOIN osm.tags as b ON(a.osm_id = b.osm_id) WHERE  a.geom && !BBOX!"
```

- error:

error Getting VTileLayer: 
unsupported type for value(map[landuse:residential name:المجاورة 3 name:ar:المجاورة 3 name:en:Neighborhood 3 place:neighbourhood]) 
with key(tags) in tags for feature 
{Feature: 840134948,
 GEO: MULTIPOLYGON (((1963 3214,1964 3214,1964 3213,1966 3212,1967 3212,1967 3213,1968 3213,1970 3215,1970 3216,1968 3218,1967 3217.300,1966 3216.700,1965 3216,1963 3214))),
  Tags: map[name:المجاورة 3 tags:map[landuse:residential name:المجاورة 3 name:ar:المجاورة 3 name:en:Neighborhood 3 place:neighbourhood] type:neighbourhood]}.

**Comment by ARolek** [comment]
@probabilty is `tags` and hstore type? If so, do you need all the tags, or can you pick a few specific ones? It looks like the issue is that the vector tile encoder doesn't like dealing with a map.

**Comment by probabilty** [comment]
Thank you

**Comment by ARolek** [comment]
Did that solve your issue?

**Comment by probabilty** [comment]
yes thank you
