### ISSUE TITLE
Link in attribution

### ISSUE THREAD

**Issue by underspica** [go-spatial/tegola#798]
Is there a way to display link in attribution field like [Mapbox](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) or [MapTiler](https://openmaptiles.github.io/osm-bright-gl-style/)?
I think this line escape all html tag: https://github.com/go-spatial/tegola/blob/v0.14.x/cmd/internal/register/maps.go#L14

**Comment by ARolek** [comment]
@underspica I think you're right. We should probably have some form of sanitization but I think escaping HTML is the wrong thing to do there. Would you be interested in sending in a PR? We're really close to cutting the v0.14.0 release so you could probably sneak it in.

**Comment by underspica** [comment]
Here is the PR #806
and some test cases https://play.golang.org/p/QL8w1w6xd54
