### ISSUE TITLE
Improve error message for gpkg register

### ISSUE THREAD

**Issue by ear7h** [go-spatial/tegola#805]
I just ran into the panic from #761 because I misspelled something in my config. 

My suggestion would be to add a check to this block
https://github.com/go-spatial/tegola/blob/a64417e76597128814ac1cf8154b7e612460700c/provider/gpkg/gpkg_register.go#L312-L323

along the lines of:
```go
_, ok := geomTableDetails[tablename]
if !ok {
    return nil, errors.New("table " + tablename + " does not exist")
}
```

**Comment by ARolek** [comment]
@ear7h seems like a good one. If you send in a PR I will review it.
