### ISSUE TITLE
Support tiers

### ISSUE THREAD

**Issue by iwpnd** [go-spatial/tegola#812]
Hi,

can you please add additional support tiers on the lower bracket of the github sponsoring?

**Comment by ARolek** [comment]
@iwpnd 👋 I can absolutely add some more support tiers. Is there an amount or something specific you're looking for? I have seen the free form tiers as well so the sponsor can choose what they want.  I will try to get that setup. 

Thanks for the interest in helping support our org!

**Comment by iwpnd** [comment]
5/10/25/50 the more tiers the lower the hurdle in my experience. :)

**Comment by ARolek** [comment]
@iwpnd I just added the custom amount option so [any amount is supported](https://github.com/sponsors/go-spatial):

![image](https://user-images.githubusercontent.com/667850/141026285-0efcb1d7-48d1-4597-a858-075610834b6e.png)

Thanks for the suggestion and interest in supporting Go Spatial!
