### ISSUE TITLE
[Feature Request]: Redis SSL connection via redis.ParseURL

### ISSUE THREAD

**Issue by iwpnd** [go-spatial/tegola#815]
Hi 👋 

Tegola does not yet support redis SSL connections and I'd like to change that, or request this feature.
e.g.: `redis://:password@host`

For this to work I'd like to add another option to `[cache]` called `uri` or `url`. If this option is set, I'd change [this](https://github.com/go-spatial/tegola/blob/8e12766c44a5749c8bed4fbb74069ec79c73ee46/cache/redis/redis.go#L60-L67) to use [`ParseURL`](https://github.com/go-redis/redis/blob/16ab0f2ac309166bfef5cde51742f84c61c1e73c/options.go#L163) to create `redis.Options` instead of creating the config manually.
ParseURL attaches the TLSConfig to the `redis.Options` if `rediss://` is part of the connection url. That way both options stay viable and tegola is a feature richer. 😁 

What do you think?

**Comment by ARolek** [comment]
@iwpnd I just looked at the [redis config](https://github.com/go-spatial/tegola/tree/v0.15.x/cache/redis#properties) and it does appear to support a `password` attribute. Is this request more around using ParseURL instead of breaking up the attributes into separate key-value pairs or is SSL not currently supported?

**Comment by iwpnd** [comment]
Hey, SSL is currently not supported. There are several ways to enable it. ParseURL is just one of them. Another would be as add a TLSConfig to redis.Options upon receiving something like `ssl=true` in the cache option. Either is fine and solves the problem.

**Comment by ARolek** [comment]
@iwpnd I would say we start with enhancing the current implementation by supporting an `ssl` config option as a boolean. I do like the idea of adding a `url` or `uri` property (I want to do this for the PostGIS provider too). Is this something you want to tackle and send in a PR for? I'm happy to help with it.

**Comment by iwpnd** [comment]
Happy to do it. :)

**Comment by ARolek** [comment]
closed via https://github.com/go-spatial/tegola/commit/bdce754abe57b76517cbed8a33e6499af0365f46. Thanks for the contribution!
