### ISSUE TITLE
openlayers

### ISSUE THREAD

**Issue by MannusEtten** [go-spatial/tegola#826]
hello

https://tegola.io/tutorials/tegola-with-olms/

i have seen this link and you use an olms-version which is compatible with openlayers 4.6.
Could you provide me those and maybe as well you json-example?

Because if i go to the repo of the olms than the release is only working for openlayers 6 and higher

**Comment by ARolek** [comment]
@MannusEtten admittedly, those docs could use a refresh. When we were using olms it was still very early stage. I have not tracked its status through to the newer versions of OpenLayers. Are you in need of olms support for OL 4.6, or can you use OL 6.0? Ideally, we could work on updating the docs so they refer to the newest version of OL.

**Comment by MannusEtten** [comment]
hi @ARolek , unfortunately, we have right now an OL 4.6.4 application in production so before we take the undergoing of the upgrade it would be nice to test it out with the current version of OL. So in that sense, it would be very much appreciated if you have the version which is compliant with 4.6.

**Comment by ARolek** [comment]
@MannusEtten I, unfortunately, don't know the exact version that was used for the tutorial. It appears the link to the demo is broken so we can't look there either (i opened an issue about this). One way to narrow down the version is to check the edit history on the associated markdown file for that tutorial: https://github.com/go-spatial/tegola-docs/commits/master/content/tutorials/tegola-with-olms.md

Based on this, I would say you can narrow your trial down to versions created prior to March 2018. If you take a look at the release page for olms I think this would put you at v2.6.1: 

https://github.com/openlayers/ol-mapbox-style/releases?page=4

LMK if that helps!

**Comment by ARolek** [comment]
I'm going to close this issue for now. LMK if you need additional help.
