### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by wroge** [go-spatial/tegola#855]
I am currently trying to get tegola up and running using the [Getting-Started](https://tegola.io/documentation/getting-started/) tutorial. Can anyone help me and tell me what I am doing wrong?
```bash
docker run --name postgis_postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=postgres -p 5432:5432  postgis/postgis
export PGPASSWORD=password
export PGUSER=postgres
export PGHOST=localhost
psql -c 'CREATE DATABASE bonn;'
psql -c "CREATE USER \"user\";"
psql bonn < bonn_osm.dump
psql -c "CREATE USER tegola;"
psql -d bonn -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO tegola;"
psql -c "ALTER USER tegola WITH PASSWORD 'password';"
// Copy config.toml to current directory and change password to 'password'
./tegola serve --config=config.toml
```
At ```localhost:8080``` i get this:
<img width="490" alt="Bildschirmfoto 2022-05-25 um 11 27 52" src="https://user-images.githubusercontent.com/44040384/170230013-68e87971-d0b1-4ad7-ae61-905032624e8e.png">

**Comment by iwpnd** [comment]
The v0.15.0 image does also not contain the viewer @ARolek - wasn’t sure if that was intentional or not.

**Comment by ARolek** [comment]
@iwpnd thats not intentional. I'm wondering if the CI ran into an issue building the UI for embedding during the release.

**Comment by gdey** [comment]
@iwpnd I think I found the issue, it lies with out build system, I am working on a fix.

**Comment by gdey** [comment]
@wroge @iwpnd  can you take a look at these [artifacts](https://github.com/go-spatial/tegola/actions/runs/2388028762)  and make sure it works as expected. Thanks.

**Comment by wroge** [comment]
It works very well, thanks for the quick fix :)
