### ISSUE TITLE
deckgl style functionality

### ISSUE THREAD

**Issue by gedw99** [go-spatial/tegola#866]
It would be good to be able to render 2d and 3d elements within the 3d maps.

I dont know how is it is to inject 3d objects into the rendering framework though. Anyone know ?

**Comment by ARolek** [comment]
@gedw99 vector tiles have "pseudo" 3d capabilities (often called 2.5d) which is achieved by encoding attributes into features like `height` that the client side renderer can use for extrusions. I know Mapbox can render 3d object but I believe they're introduced as external files and are not part of the vector tiles themselves. [Here's some documentation](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/)

3D terrain is usually done with DEM raster tiles, so again not specific to tegola.
