### ISSUE TITLE
Slow tile load speed - Bonn tutorial example

### ISSUE THREAD

**Issue by diehl** [go-spatial/tegola#876]
Hello, 

After loading the Bonn data and firing up the server, I'm noticing that the tiles will occasionally take order seconds to load. Any advice on how to diagnose this latency and address the issue? I need to see far more responsive load times for my application. 

Each time I reload the server page (localhost:8080), I'm seeing a latency of about 8-10 seconds to load all the tiles. 

Thanks in advance for any pointers!

**Comment by iwpnd** [comment]
Hey 👋🏻 

Im not familiar with the Bonn example. Can you share a link so I can retrace your steps? Without additional information I can only guess.

1. your geometry column does not have an index
2. nah, I guess that's it 😅

**Comment by diehl** [comment]
@iwpnd haha! That might very well be it. I'm brand new to PostGIS so I was following [the instructions here](https://tegola.io/documentation/getting-started/) in the Getting Started guide to the letter.

**Comment by iwpnd** [comment]
Execute this

```
SELECT * FROM all_roads 
WHERE ST_DWithin(
	ST_SetSRID(ST_MakePoint(7.101303103, 50.73471081), 4326),
	wkb_geometry,
	0.001
)
```
will take approx 500ms.

Then do this:

```
CREATE INDEX geom_index_all_roads ON all_roads USING GIST (wkb_geometry);
```
and afterwards this again:
```
SELECT * FROM all_roads 
WHERE ST_DWithin(
	ST_SetSRID(ST_MakePoint(7.101303103, 50.73471081), 4326),
	wkb_geometry,
	0.001
)
```
this should be a fraction of the first try now.

do the former for all of the tables you want to use in tegola:

```
CREATE INDEX geom_index_main_roads ON main_roads USING GIST (wkb_geometry);
CREATE INDEX geom_index_lakes ON lakes USING GIST (wkb_geometry);
```

now you should be okay

**Comment by diehl** [comment]
@iwpnd Thanks so much. I've created these indexes and verified the speedup at the command line. And unfortunately I'm seeing the same behavior. I stopped and restarted the Tegola server in case that was an issue. No joy. 

I'm examining responsiveness two ways. One is through the Tegola viewer and another is through a visualization of the same data using PyDeck. The Tegola viewer seems to be more responsive now after the initial load. But when you first load the viewer, the tiles still take on the order of 5-10 seconds to fully load. 

In PyDeck, the story is a little more complicated. As I zoom in and cross from the lowest resolution tileset to the next zoom level, it always takes order 5 seconds to load the next tileset. So bizarre. 

Any other thoughts on what might be happening here? I've got nothing at present.

**Comment by iwpnd** [comment]
I'll check back after dinner. I have some ideas :)

**Comment by diehl** [comment]
@iwpnd awesome - thank you sir! :-)

**Comment by iwpnd** [comment]
Make sure you're running the latest version of tegola first.

Aight, let's add a small file cache to your tegola config at the top level.

```
[cache]
type="file"             # cache type
basepath="/tmp/tegola"  # cache specific config
````

then we can add a maxage header to your webserver response. that'll tell mapbox to cache your requests in the browser for a couple of minutes before it requests the same tile again.

```
[webserver.headers]
Cache-Control = "maxage=120" # seconds
```

Then we can try the `mvt_postgis` provider. And we do it like so:

```
[[providers]]
name = "bonn" 
type = "mvt_postgis" 
host = "localhost"  
port = 5432 
database = "bonn" 
user = "tegola" 
password = "" 
srid = 4326  
```

an mvt_postgis provider requires you to change a few things in your layers:

```
  [[providers.layers]]
  name = "road"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM all_roads WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "main_roads"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM main_roads WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "lakes"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM lakes WHERE wkb_geometry && !BBOX!"
```

That should get you some way further. @diehl 

@ARolek and @gdey, something is off with the postgis provider. It is not the first user we have to suggest to use the mvt_postgis provider instead. I cannot tell if this is due to the pg update, or whether it has been that way before, as I started with tegola and the mvt_provider right away.

**Comment by iwpnd** [comment]
I created a small repo that allows you start the bonn example easier in a couple of containers.

https://github.com/iwpnd/tegola-example-bonn

- clone, 
- download the bonn data and unzip it in `bin/`, 
- `docker compose up` and 
- `PGPASSWORD=postgres sh bin/init.sh` 

Now you can check the data out in the viewer on `:8080` for the `mvt_postgis` provider or `:8081` for the `postgis`provider.

**Comment by diehl** [comment]
@iwpnd Awesome. I will give this all a whirl and report back. Thank you sir!

**Comment by ARolek** [comment]
@iwpnd 

> @ARolek and @gdey, something is off with the postgis provider. It is not the first user we have to suggest to use the mvt_postgis provider instead. I cannot tell if this is due to the pg update, or whether it has been that way before, as I started with tegola and the mvt_provider right away.

Yeah, the `postgis` provider uses a geometry processing system that was rolled in the early days of tegola and is part of the [geom[(https://github.com/go-spatial/geom) package. This was all built before PostGIS introduced MVT encoding natively. The processing system works for the most part, but is rather slow compared to `mvt_postgis`. Unfortunately we haven't had a lot of time to make improvements to the geometry processing. 

The `mvt_postgis` provider is favored over `postgis` at the current time.

**Comment by diehl** [comment]
@iwpnd So I started by updating the `[[providers]]` and `[[providers.layers]]` sections. I now have the following in my `config.toml` file. FYI there's a typo in your SQL select statement above for the `road` layer. SELECT is repeated twice. What I'm seeing when I try to fire up the server is the following error.

```
2022-07-28 17:18:47 [INFO] config.go:317: loading local config (config.toml)
2022-07-28 17:18:47 [WARN] postgis.go:332: Connecting to PostGIS with connection parameters is deprecated. Use 'uri' instead.
Error: could not register providers: error fetching geometry type for layer (road): layer (road) returned unsupported geometry type (<nil>)
```
```
# register data providers
[[providers]]
name = "bonn"           # provider name is referenced from map layers
type = "mvt_postgis"    # the type of data provider. currently only supports postgis
host = "localhost"      # postgis database host
port = 5432             # postgis database port
database = "bonn"       # postgis database name
user = "tegola"         # postgis database user
password = ""           # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "road"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM all_roads WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "main_roads"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM main_roads WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "lakes"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, name, ogc_fid FROM lakes WHERE wkb_geometry && !BBOX!"
```

**Comment by iwpnd** [comment]
fixed, and added the geometry_type manually.

**Comment by diehl** [comment]
@iwpnd Thank you sir! I updated the `[[providers.layers]]` sections and am now seeing the performance I hoped for: both in the Tegola viewer and in PyDeck. 

For the record, I did not add the `[cache]` and `[webserver.headers]` sections to the config.toml file to get the performance boost.

**Comment by ARolek** [comment]
@iwpnd I think your example code should take over the getting started guide in the docs. We should really push new adopters to `mvt_postgis` going forward. Thanks for helping put that together.
