### ISSUE TITLE
unable to serve geopackage

### ISSUE THREAD

**Issue by nabazgharib** [go-spatial/tegola#889]
version: v0.15.2
       git: detached @ 6387c67
build tags: !noAzblobCache !noGpkgProvider !noPostgisProvider !noPrometheusObserver !noRedisCache !noS3Cache !noViewer !pprof cgo
 ui viewer: e70a1303

os: windows 10

when I server the service, I get this in browser:
![image](https://user-images.githubusercontent.com/4522358/199448864-7d8d683d-26d2-4374-9ef8-6666173a6d97.png)

**Comment by ARolek** [comment]
@nabazgharib were you ever able to figure this out?

**Comment by nabazgharib** [comment]
@ARolek ,
No I have not been able to figure out the issue.
I downloaded the latest version, and I am getting this message on checking the version:
`
![image](https://user-images.githubusercontent.com/4522358/209545681-98f9bdbb-50de-42b2-988a-c77617de1db9.png)
`

**Comment by gdey** [comment]
@nabazgharib No, errors or stack dumps or anything on the console? Are you using your own build or the official one?

**Comment by nabazgharib** [comment]
Thank you it works now,
I should close the issue.
