### ISSUE TITLE
Google Cloud Storage cache adapter

### ISSUE THREAD

**Issue by matheusmatos** [go-spatial/tegola#890]
Hi guys,

Is anyone working on a GCP caching adapter?

Would a pull request implementing this be welcome?

**Comment by ARolek** [comment]
@matheusmatos I'm not aware of anyone tacking this issue and a PR would be welcome!

**Comment by matheusmatos** [comment]
Great! I started working on it in this branch:

[https://github.com/matheusmatos/tegola/tree/@matheusmatos/cache-gcp](https://github.com/matheusmatos/tegola/tree/%40matheusmatos/cache-gcp)

I will share the progress!

**Comment by ARolek** [comment]
Nice! I have 0 experience with that service so all I can do I help with code review from an implementation standpoint, but not a correct / best practices standpoint specific to the service.

**Comment by matheusmatos** [comment]
Excellent! In fact, I've experience with GCP but not so much with GoLang. I opened the PR (#891) but I think it's not ready to be merged yet.

I needed to add the [cloud.google.com/go/storage](http://cloud.google.com/go/storage) package and it created a lot of files inside vendor folder. Is it correct for this to be committed to Git?

**Comment by ARolek** [comment]
Yeah vendoring will copy all the files to the vendor directory. This is our preferred approach. Ideally the vendoring happens in a separate commit from the implementation.

**Comment by matheusmatos** [comment]
Okay, I'll resend as two commits, implementation and vendoring. Just a moment.

**Comment by matheusmatos** [comment]
I sent the two commits. I'm not sure if the vendor commit is correct. Any help is appreciated. Thanks!

**Comment by dthib** [comment]
Hi @ARolek, thanks for the great work. I am interested in this PR too (thanks @matheusmatos too!). Any news when it can be merged ?
Best

**Comment by dthib** [comment]
Ok great thanks for the reply @ARolek
