### ISSUE TITLE
Serve vector tiles using Tegola and Maplibre-gl-native on android app

### ISSUE THREAD

**Issue by AmirOsman2020** [go-spatial/tegola#912]
Hello tegola community, I've been trying to use tegola vector tiles on my android app using maplibre-gl-native, the server is working fine and my app working fine the problem is with the style, screenshot below:

![Screenshot_20230314_135214_com clone uberclone](https://user-images.githubusercontent.com/90759789/224993187-abe3c6fa-f46b-4880-9c5b-8940587958e0.jpg)

I want it to look like mapbox, the tutorial example on tegola website showed how to use tegola with maplibre-gl-js by using styles from maplibre server and I have to get an access token, the only reason I wanted to self-host tegola and use open source solution like maplibre-gl-native is because I don't want to use external services, I already managed to do this using Tileserver-gl which allows me to add a styled map to maplibre-gl-native without using an external service.
Anyone can help???

The below screenshot is the same app using maplibre-gl-native and tileserver-gl as the tile server without using any external styles or services

![Screenshot_20230314_140930_com clone uberclone](https://user-images.githubusercontent.com/90759789/224997497-611a82c1-4765-4a49-aa93-fadb5cd82cdd.jpg)

**Comment by ARolek** [comment]
> So why Arabic labels works on the web but they don't work on my android app, is the problem with maplibre-gl-native?

If you can see the labels correctly on web, but not native, and you're using the same tile source then this is likely a client side issue. You might need to look at what fonts are available on Android. 

I'm going to close this issue as this appears to be on the client side rather than an issue with tegola.
