### ISSUE TITLE
Support uuid type for gid column

### ISSUE THREAD

**Issue by philhug** [go-spatial/tegola#929]
I'm trying to use uuid as the feature id field, but this does not seem to work.
Does anyone have a workaround for this?

postgis.go:1066: TEGOLA_SQL_DEBUG:EXECUTE_SQL: returned error ERROR: mvt_agg_transfn: Could not find column 'id' of integer type (SQLSTATE XX000)

**Comment by iwpnd** [comment]
I have to do a lot of digging again, but I'm 95% sure that this is an issue with the mvt spec, not tegola.

**Comment by ARolek** [comment]
@philhug what @iwpnd said is correct, the MVT spec only supports uint64 values for the id. 

If you need to store a `uuid` in a feature, just add a new tag, called `uuid` or `feature_id` or whatever. It wont occupy the `id` field in the feature, but instead a tag.

**Comment by iwpnd** [comment]
were you able to fix the issue @philhug?
