### ISSUE TITLE
GPKG coordinate conversion unavailable

### ISSUE THREAD

**Issue by frafra** [go-spatial/tegola#939]
Hi,
it would be nice to support reprojection for gpkg files. This is the error I see:

```
[ERROR] map.go:345: err fetching tile (z: 11, x: 1022, y: 1022) features: error converting point: don't know how to convert from 25833 to 3857.
```

**Comment by ARolek** [comment]
@frafra I don't think geopackages have any projection support. If we added something like #115 you would have access to proj and you could re-project. Is Geopackage a hard requirement for you?

**Comment by frafra** [comment]
@ARolek I was just testing tegola in a small project that relies on geopackages, that is all. I was able to reproject using gdal like this:
`ogr2ogr -f gpkg -t_srs EPSG:3857 "$output" "$input"`, which seems reasonable to me.

**Comment by ARolek** [comment]
@frafra ok. I think that's the best approach. Usually you want to avoid re-projecting at runtime if you can. I'm going to close this issue out as you seem to have a good resolution.
