### ISSUE TITLE
Push images for more architectures to Docker Hub registry

### ISSUE THREAD

**Issue by manastyretskyi** [go-spatial/tegola#940]
Hi, my name is Liubomyr and I'm a big fan of your project. I'm writing to you today because I have a suggestion that I think could improve it.

Sadly, currently `gospatial/tegola` only has images for `linux/amd64` architecture, which means that it is not possible to use official image on different architectures like `linux/arm64`.
I think it would be great to add official images for other architectures. The [buildx](https://github.com/docker/buildx) that can be used to build multi-platform images. There is also an official [GitHub action](https://github.com/docker/setup-buildx-action) that can be used as well.

I would be happy to help with this, if needed, to make sure that it is possible to use official image on architectures different from `linux/amd64`.

**Comment by ARolek** [comment]
@manastyretskyi yep let's do it! I was actually thinking about this exact update yesterday. If you want to send in the CI update I will give it a review. Here's the GH Action we should leverage: https://github.com/docker/setup-buildx-action

**Comment by iwpnd** [comment]
can I propose we move to goreleaser and do all of that for us?

**Comment by ARolek** [comment]
@iwpnd I haven't used goreleaser but I'm not opposed to it. Adding the buildx action is not that big of a lift though. Do you think it's worth adding goreleaser as a project dependency?
