### ISSUE TITLE
Filename extension for file cache

### ISSUE THREAD

**Issue by wroge** [go-spatial/tegola#965]
It would be nice if one could specify the file extension for tiles generated via file cache or if the file extension were set to .pbf by default.  
Or did I overlook a setting?

**Comment by ARolek** [comment]
@wroge I don't think you overlooked a setting, we just don't write the extension to the cache. Can you help me understand the problem you're looking to address?

**Comment by wroge** [comment]
The last timeI thought the last time I created tiles directly into the s3 bucket that they had a pbf ending. But I was probably wrong. The problem I thought I had was that the files have different extensions depending on whether they were created in an s3 bucket or local. Now I have tried again and the files have no pbf extension...
