### ISSUE TITLE
Write config file for tables having ' - ' and capital letters in their name.

### ISSUE THREAD

**Issue by MuhammadYasirAliKhan786** [go-spatial/tegola#969]
Hi, I am trying to write a config file contains tables having hyphen character ' - ' and capital letters in their name. But its failed with the following error:

tegola-server | Error: could not register providers: could not generate sql, for layer(Registered_Parks_and_Gardens): ERROR: relation "registered_parks_and_gardens" does not exist (SQLSTATE 42P01).

Or:

tegola-server  | Error: could not register providers: could not generate sql, for layer(civil-parish): ERROR: syntax error at or near "-" (SQLSTATE 42601).

I search through internet but unable to find any solution. Any thoughts on this?

**Comment by iwpnd** [comment]
Please provide an obfuscated SQL statement.

My guess is that you'll have to put the table name in `'`.

**Comment by MuhammadYasirAliKhan786** [comment]
Thankyou @iwpnd , you were right, it was only the matter of putting table names inside `''`.
