### ISSUE TITLE
provider/postgis: Clean out deprecated connection params

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#979]
In v0.15.0 support for a connection string uri was added to provider/postgis. When this change was made, we marked the [old connection params as deprecated](https://github.com/go-spatial/tegola/tree/master/provider/postgis#deprecated-connection-properties). These params now need to be removed. This issue is for tracking this removal from the following places:

- [ ] `provider/postgis`:  This package needs to remove support for the old connection params. The README should also be updated.
- [ ] `.github/`: The CI uses the old connection params in a few places and needs to be migrated.

**Comment by ARolek** [comment]
> I can take it.

That would be awesome! Your recent PR made me realize this hasn't been done but should absolutely be cleaned up. I'm on a "purge all the unnecessary things" kick right now 😉 

> Do you think it makes sense to create Github project to collect open work like this

I would absolutely be in favor of this. We could then organize issues based on priority if contributors are looking to pick up an issue. I can spin up a project called "Roadmap" and we can start adding issues to it. How does that sound?

**Comment by iwpnd** [comment]
Great 👌🏻 let’s do that

**Comment by ARolek** [comment]
@iwpnd done. I also invited you to it so you can help groom the backlog ;-)

**Comment by ARolek** [comment]
@iwpnd have you had a chance to look at this issue? I'm hoping to include these changes in the upcoming release. The upcoming release has a lot of vuln squashing in it, so I would like to get a version cut in the not too distant future. LMK if you want to tag team this one.

**Comment by iwpnd** [comment]
Gosh 19d ago already. I'm swamped at work right now and happy to not touch the keyboard in the evening. But I do have a three hour train ride on Wednesday reserved for it. ☝🏻🤞🏻

**Comment by ARolek** [comment]
@iwpnd No worries!!

> I'm swamped at work right now and happy to not touch the keyboard in the evening.

I can relate. A lot to juggle right now. No pressure. 

> But I do have a three hour train ride on Wednesday reserved for it.

Excellent. Feel free to push up a branch if you need some help along the way. Thanks for tackling this one!
